package engine

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/hoshinoht/shiori/internal/ojson"
	"github.com/hoshinoht/shiori/internal/testutil"
)

// D.1 approved design changes (contracts §11, 2026-09-30) intentionally
// change the output of some oracle vectors. The oracle files stay
// untouched; testdata/d1/expectations.json lists every such vector with
// the SHA-256 of the new (root-normalized) Go output, which pins it. Each
// listed vector must also pass a comparator proving that only the
// approved change differs from the oracle:
//
//   - workplan_resume (A): same machine fields (ids, hashes, counts,
//     totals, freshness, retrieval); every display string is the oracle's
//     string or a compatible truncation of the same text; page items are
//     the same items in the same order (a prefix of either side); page
//     arithmetic and omission counts are self-consistent.
//   - workplan_read with a filter (B): the slice is exactly the oracle's
//     document minus phases/findings/notes, the same selection, no
//     Markdown content, the dependency view restricted to the selection
//     and a correct slice descriptor.
//   - workplan_validate / workplan_doctor (C, F): removing the additive
//     members (warnings, strayArtifacts...) yields the oracle output
//     byte-for-byte, or passes the vector's older approved comparator
//     (D1/D5/D6).
//
// SHIORI_D1_UPDATE=1 rewrites the expectation hashes (review the diff).

const d1ExpectationsFile = "d1/expectations.json"

type d1Expectation struct {
	Change          string `json:"change"`
	OutputSha256    string `json:"outputSha256"`
	RawOutputLength int    `json:"rawOutputLength"`
}

type d1File struct {
	Note    string                   `json:"note"`
	Vectors map[string]d1Expectation `json:"vectors"`
}

var (
	d1Once    sync.Once
	d1Loaded  d1File
	d1Mu      sync.Mutex
	d1Updated = map[string]d1Expectation{}
)

func d1Update() bool { return os.Getenv("SHIORI_D1_UPDATE") == "1" }

func d1Expectations(t testing.TB) map[string]d1Expectation {
	d1Once.Do(func() {
		data, err := os.ReadFile(testutil.Testdata(d1ExpectationsFile))
		if err == nil {
			err = json.Unmarshal(data, &d1Loaded)
		}
		if err != nil && !d1Update() {
			t.Fatalf("reading %s: %v", d1ExpectationsFile, err)
		}
		if d1Loaded.Vectors == nil {
			d1Loaded.Vectors = map[string]d1Expectation{}
		}
	})
	return d1Loaded.Vectors
}

// d1Record stores a new expectation in update mode.
func d1Record(id string, x d1Expectation) {
	d1Mu.Lock()
	defer d1Mu.Unlock()
	d1Updated[id] = x
}

// d1Write merges recorded expectations for the given prefixes into the file.
func d1Write(t *testing.T, prefixes ...string) {
	if !d1Update() {
		return
	}
	cur := d1Expectations(t)
	out := map[string]d1Expectation{}
	for id, x := range cur {
		owned := false
		for _, p := range prefixes {
			owned = owned || strings.HasPrefix(id, p)
		}
		if !owned {
			out[id] = x
		}
	}
	d1Mu.Lock()
	for id, x := range d1Updated {
		out[id] = x
	}
	d1Mu.Unlock()
	f := d1File{
		Note:    "D.1 approved design changes (docs/contracts.md §11): oracle vectors whose Go output intentionally differs, with the SHA-256 and UTF-16 length of the pinned Go output (root-normalized). Generated by SHIORI_D1_UPDATE=1 go test ./internal/engine; each entry also passes a comparator against the unchanged oracle vector.",
		Vectors: out,
	}
	data, _ := json.MarshalIndent(f, "", "  ")
	if err := os.MkdirAll(testutil.Testdata("d1"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testutil.Testdata(d1ExpectationsFile), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	d1Loaded.Vectors = out
	t.Logf("wrote %s (%d vectors)", d1ExpectationsFile, len(out))
}

// d1Change classifies a vector by tool and input.
func d1Change(v *vector) string {
	switch v.Call.Tool {
	case "workplan_resume":
		return "A resume budgeting"
	case "workplan_read":
		return "B filtered read slice"
	case "workplan_validate", "workplan_doctor":
		return "C/F additive warnings"
	}
	return ""
}

// d1Candidate reports whether a successful vector run goes through the
// D.1 path: it is listed, or (update mode) its output differs from the
// oracle in a way a D.1 comparator covers.
func d1Candidate(t *testing.T, v *vector, got string) bool {
	if _, ok := d1Expectations(t)[v.ID]; ok {
		return true
	}
	if !d1Update() || v.Expect.Kind == "error" || d1Change(v) == "" || normEngineText(got) == normEngineText(oracleText(v)) {
		return false
	}
	switch v.Call.Tool {
	case "workplan_read":
		var in struct {
			PhaseID *string `json:"phaseId"`
			StepID  *string `json:"stepId"`
		}
		json.Unmarshal(v.Call.Input, &in)
		return in.PhaseID != nil || in.StepID != nil
	case "workplan_validate", "workplan_doctor":
		_, removed, err := stripD1Additive(got)
		return err != nil || removed > 0
	}
	return true
}

// checkD1 runs the D.1 comparator for a listed (or, in update mode, a
// diverging) vector and checks the pinned output hash.
func checkD1(t *testing.T, v *vector, root testutil.Root, text string) (outcome, string) {
	t.Helper()
	got := root.Normalize(text)
	change := d1Change(v)
	if normEngineText(got) == normEngineText(oracleText(v)) {
		t.Fatalf("listed in %s but identical to the oracle; remove the entry", d1ExpectationsFile)
	}
	var err error
	switch v.Call.Tool {
	case "workplan_resume":
		checkResumeInvariants(t, v, text)
		// Compare at the generation root: the oracle truncated some
		// absolute paths, so they were never $ROOT-substituted.
		err = d1ResumeCompat(strings.ReplaceAll(text, root.Path, root.GenRoot),
			strings.ReplaceAll(oracleText(v), "$ROOT", root.GenRoot))
	case "workplan_read":
		err = d1ReadSlice(v, got)
	case "workplan_validate", "workplan_doctor":
		err = d1Additive(v, got)
	default:
		err = fmt.Errorf("no D.1 comparator for %s", v.Call.Tool)
	}
	if err != nil {
		t.Fatalf("D.1 %s comparator: %v", change, err)
	}
	budgeted := v.Call.Tool == "workplan_resume"
	if d1Update() {
		if !budgeted || root.SameLength() {
			d1Record(v.ID, d1Expectation{Change: change, OutputSha256: sha(got), RawOutputLength: ojson.UTF16Len(text)})
		}
		return outDivergence, v.ID + ": D.1 " + change + " (recorded)"
	}
	x, ok := d1Expectations(t)[v.ID]
	if !ok {
		t.Fatalf("output differs from the oracle and the vector is not listed in %s", d1ExpectationsFile)
	}
	if !budgeted || root.SameLength() {
		if sha(got) != x.OutputSha256 {
			t.Fatalf("D.1 pinned output changed: sha %s want %s (SHIORI_D1_UPDATE=1 to re-pin after review)", sha(got), x.OutputSha256)
		}
		if root.SameLength() && ojson.UTF16Len(text) != x.RawOutputLength {
			t.Fatalf("D.1 raw length %d want %d", ojson.UTF16Len(text), x.RawOutputLength)
		}
	}
	return outDivergence, v.ID + ": D.1 " + x.Change
}

// oracleText is the vector's expected output text.
func oracleText(v *vector) string {
	if v.Expect.OutputText != nil {
		return *v.Expect.OutputText
	}
	p, _ := ojson.Parse(v.Expect.Output)
	return string(ojson.Pretty(p.Value))
}

// ---- A: resume ----

var d1ResumeSkip = map[string]bool{
	"safety.overflow": true, "safety.truncatedDangerFieldCount": true, "safety.overflowPointers": true,
	"safety.omittedDangerCounts": true, "safety.unverifiedWarningsOmitted": true,
	"truncatedFields": true, "truncatedFieldCount": true, "truncatedFieldPathsOmitted": true,
	"page.returned": true, "page.omitted": true, "page.nextCursor": true,
}

var d1ResumePrefixLists = map[string]bool{
	"checkpoint.blockers": true, "checkpoint.guardrails": true, "checkpoint.references": true,
	"checkpoint.recentValidation": true, "workplan.scope": true, "workplan.nonGoals": true,
	"workplan.constraints": true, "workplan.relevantFiles": true, "safety.highFindings": true,
	"safety.unverifiedWarnings": true, "currentDependencies.references": true, "page.items": true,
}

// truncCompatible reports whether a and b are the same text, possibly
// shortened with a trailing ellipsis on either side.
func truncCompatible(a, b string) bool {
	if a == b {
		return true
	}
	ta, tb := strings.HasSuffix(a, "…"), strings.HasSuffix(b, "…")
	sa, sb := strings.TrimSuffix(a, "…"), strings.TrimSuffix(b, "…")
	switch {
	case ta && tb:
		return strings.HasPrefix(sa, sb) || strings.HasPrefix(sb, sa)
	case ta:
		return strings.HasPrefix(b, sa)
	case tb:
		return strings.HasPrefix(a, sb)
	}
	return false
}

func d1Compat(g, w any, path string) error {
	if d1ResumeSkip[path] {
		return nil
	}
	switch wv := w.(type) {
	case map[string]any:
		gv, ok := g.(map[string]any)
		if !ok {
			return fmt.Errorf("%s: type differs", path)
		}
		if len(gv) != len(wv) {
			return fmt.Errorf("%s: member sets differ", path)
		}
		for k, x := range wv {
			y, ok := gv[k]
			if !ok {
				return fmt.Errorf("%s: missing member %s", path, k)
			}
			p := k
			if path != "" {
				p = path + "." + k
			}
			if err := d1Compat(y, x, p); err != nil {
				return err
			}
		}
		return nil
	case []any:
		gv, ok := g.([]any)
		if !ok {
			return fmt.Errorf("%s: type differs", path)
		}
		n := len(wv)
		if d1ResumePrefixLists[path] {
			if len(gv) < n {
				n = len(gv)
			}
		} else if len(gv) != len(wv) {
			return fmt.Errorf("%s: length %d want %d", path, len(gv), len(wv))
		}
		for i := 0; i < n; i++ {
			if err := d1Compat(gv[i], wv[i], path); err != nil {
				return fmt.Errorf("[%d] %w", i, err)
			}
		}
		return nil
	case string:
		gs, ok := g.(string)
		if !ok || !truncCompatible(gs, wv) {
			return fmt.Errorf("%s: %q is not a truncation-compatible form of %q", path, g, wv)
		}
		return nil
	}
	if !reflect.DeepEqual(g, w) {
		return fmt.Errorf("%s: %v want %v", path, g, w)
	}
	return nil
}

func num(v any) int {
	n, _ := v.(json.Number).Int64()
	return int(n)
}

// d1ResumeCompat compares a D.1 resume packet with the oracle's and checks
// its self-consistency and readability invariants.
func d1ResumeCompat(got, want string) error {
	g, err := decodeAny(got)
	if err != nil {
		return err
	}
	w, err := decodeAny(want)
	if err != nil {
		return err
	}
	gm := g.(map[string]any)
	if err := d1Compat(g, w, ""); err != nil {
		return err
	}
	pg := gm["page"].(map[string]any)
	items := pg["items"].([]any)
	ret, om, off, tot := num(pg["returned"]), num(pg["omitted"]), num(pg["offset"]), num(pg["total"])
	if ret != len(items) || ret+om+off != tot {
		return fmt.Errorf("page arithmetic: returned %d omitted %d offset %d total %d", ret, om, off, tot)
	}
	if _, isStr := pg["nextCursor"].(string); isStr != (om > 0) {
		return fmt.Errorf("nextCursor presence does not match omitted=%d", om)
	}
	if om > 0 && ret == 0 {
		return fmt.Errorf("page does not progress")
	}
	wp := gm["workplan"].(map[string]any)
	cp := gm["checkpoint"].(map[string]any)
	sf := gm["safety"].(map[string]any)
	odc := sf["omittedDangerCounts"].(map[string]any)
	for _, c := range []struct {
		obj        map[string]any
		list, tot  string
		omittedKey string
	}{{wp, "constraints", "constraintsTotal", "constraints"}, {wp, "scope", "scopeTotal", "scope"}, {wp, "nonGoals", "nonGoalsTotal", "nonGoals"},
		{cp, "blockers", "blockersTotal", "blockers"}, {sf, "highFindings", "highFindingsTotal", "highFindings"}} {
		if l, ok := c.obj[c.list].([]any); ok {
			if num(c.obj[c.tot])-len(l) != num(odc[c.omittedKey]) {
				return fmt.Errorf("omittedDangerCounts.%s inconsistent", c.omittedKey)
			}
		}
	}
	// Readability: outside the single-item emergency levels no display
	// string is shortened below the title minimum, and paths are never
	// shortened.
	if ret > 1 {
		var short []string
		var walk func(x any, p string)
		walk = func(x any, p string) {
			switch xv := x.(type) {
			case map[string]any:
				for k, y := range xv {
					walk(y, p+"."+k)
				}
			case []any:
				for _, y := range xv {
					walk(y, p+"[]")
				}
			case string:
				// One unit of slack: a surrogate pair is never split.
				if strings.HasSuffix(xv, "…") && ojson.UTF16Len(xv) < resumeMinTitle-1 {
					short = append(short, p)
				}
			}
		}
		walk(g, "")
		if len(short) > 0 {
			return fmt.Errorf("strings shortened below the readable minimum with %d items: %v", ret, short)
		}
		for _, k := range []string{"path", "planFile"} {
			if s, _ := gm[k].(string); strings.HasSuffix(s, "…") {
				return fmt.Errorf("%s was truncated", k)
			}
		}
	}
	return nil
}

// ---- B: filtered read ----

func d1ReadSlice(v *vector, got string) error {
	g, err := decodeAny(got)
	if err != nil {
		return err
	}
	gm := g.(map[string]any)
	wm := expectedAny(v).(map[string]any)
	for _, k := range []string{"path", "planHash", "stateHash", "selection"} {
		if !jsonEqual(gm[k], wm[k]) {
			return fmt.Errorf("%s differs", k)
		}
	}
	ww := wm["workplan"].(map[string]any)
	header := map[string]any{}
	for k, x := range ww {
		if k != "phases" && k != "reviewFindings" && k != "notes" {
			header[k] = x
		}
	}
	if !jsonEqual(gm["workplan"], header) {
		return fmt.Errorf("workplan header is not the oracle document minus phases/findings/notes")
	}
	wplan := wm["plan"].(map[string]any)
	if !jsonEqual(gm["plan"], map[string]any{"path": wplan["path"], "exists": wplan["exists"]}) {
		return fmt.Errorf("plan must carry path/exists without Markdown content")
	}
	// Dependencies restricted to the selection (independent restatement).
	sel := map[[2]string]bool{}
	for _, ph := range wm["selection"].(map[string]any)["phases"].([]any) {
		pm := ph.(map[string]any)
		for _, st := range pm["steps"].([]any) {
			sel[[2]string{pm["id"].(string), st.(map[string]any)["id"].(string)}] = true
		}
	}
	key := func(x any) [2]string {
		m := x.(map[string]any)
		return [2]string{m["phaseId"].(string), m["stepId"].(string)}
	}
	wd := wm["dependencies"].(map[string]any)
	deps := []any{}
	refs := map[[2]string]bool{}
	for _, en := range wd["dependencies"].([]any) {
		keep := sel[key(en)]
		for _, r := range en.(map[string]any)["dependsOn"].([]any) {
			keep = keep || sel[key(r)]
		}
		if keep {
			deps = append(deps, en)
			for _, r := range en.(map[string]any)["dependsOn"].([]any) {
				refs[key(r)] = true
			}
		}
	}
	terms := []any{}
	for _, ts := range wd["terminalSummaries"].([]any) {
		if refs[key(ts)] || sel[key(ts)] {
			terms = append(terms, ts)
		}
	}
	wantDeps := map[string]any{"recorded": wd["recorded"], "dependencies": deps, "terminalSummaries": terms, "issues": wd["issues"]}
	if !jsonEqual(gm["dependencies"], wantDeps) {
		return fmt.Errorf("dependencies are not the oracle view restricted to the selection")
	}
	steps := 0
	for _, ph := range ww["phases"].([]any) {
		steps += len(ph.(map[string]any)["steps"].([]any))
	}
	wantSlice := map[string]any{
		"filtered": true, "phaseCount": json.Number(fmt.Sprint(len(ww["phases"].([]any)))),
		"stepCount": json.Number(fmt.Sprint(steps)), "findingCount": json.Number(fmt.Sprint(len(ww["reviewFindings"].([]any)))),
		"noteCount": json.Number(fmt.Sprint(len(ww["notes"].([]any)))), "notesIncluded": false, "markdownIncluded": false,
		"dependenciesFiltered": true, "full": "workplan_read id=" + ww["id"].(string),
	}
	if !jsonEqual(gm["slice"], wantSlice) {
		return fmt.Errorf("slice descriptor %v want %v", gm["slice"], wantSlice)
	}
	if len(gm) != 8 {
		return fmt.Errorf("unexpected members: %d", len(gm))
	}
	return nil
}

// ---- C/F: additive members ----

var d1WarningPrefixes = []string{
	"planFile: Linked Markdown is not the generated rendering of the plan JSON",
	"Orphaned sidecar ",
	"Unclassified file ",
}

func d1CheckWarnings(v ojson.Value) error {
	if v.Kind() != ojson.Array || len(v.Elems()) == 0 {
		return fmt.Errorf("warnings must be a nonempty array when present")
	}
	for _, w := range v.Elems() {
		ok := false
		for _, p := range d1WarningPrefixes {
			ok = ok || strings.HasPrefix(w.Str(), p)
		}
		if !ok {
			return fmt.Errorf("unexpected warning %q", w.Str())
		}
	}
	return nil
}

// stripD1Additive removes the D.1 additive members, checking them.
func stripD1Additive(text string) (string, int, error) {
	p, err := ojson.Parse([]byte(text))
	if err != nil {
		return "", 0, err
	}
	removed := 0
	var ms []ojson.Member
	for _, m := range p.Value.Members() {
		switch m.Key {
		case "warnings":
			if err := d1CheckWarnings(m.Value); err != nil {
				return "", 0, err
			}
			removed++
			continue
		case "strayArtifacts", "strayArtifactCount", "omittedStrayArtifacts":
			removed++
			continue
		case "plans":
			var plans []ojson.Value
			for _, pl := range m.Value.Elems() {
				var pms []ojson.Member
				for _, x := range pl.Members() {
					if x.Key == "warnings" {
						if err := d1CheckWarnings(x.Value); err != nil {
							return "", 0, err
						}
						removed++
						continue
					}
					pms = append(pms, x)
				}
				plans = append(plans, ojson.ObjectValue(pms))
			}
			if plans == nil {
				plans = []ojson.Value{}
			}
			m.Value = ojson.ArrayValue(plans)
		}
		ms = append(ms, m)
	}
	return string(ojson.Pretty(ojson.ObjectValue(ms))), removed, nil
}

func d1Additive(v *vector, got string) error {
	stripped, removed, err := stripD1Additive(got)
	if err != nil {
		return err
	}
	if removed == 0 {
		return fmt.Errorf("no D.1 additive member present")
	}
	if div, ok := divergences[v.ID]; ok {
		return div.check(v, stripped)
	}
	want := oracleText(v)
	if stripped != want || sha(stripped) != v.Expect.OutputSha256 {
		return fmt.Errorf("output without the additive members differs from the oracle\n%s", firstDiff(stripped, want))
	}
	return nil
}

// d1Summary lists the listed vectors by change (for the STATUS table).
func d1Summary(m map[string]d1Expectation) string {
	by := map[string]int{}
	for _, x := range m {
		by[x.Change]++
	}
	var keys []string
	for k := range by {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var parts []string
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%d", k, by[k]))
	}
	return strings.Join(parts, " ")
}
