package engine

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/hoshinoht/shiori/internal/model"
	"github.com/hoshinoht/shiori/internal/ojson"
	"github.com/hoshinoht/shiori/internal/snapshot"
	"github.com/hoshinoht/shiori/internal/testutil"
)

// D.3.1 approved design changes (contracts §14, 2026-09-30). The oracle
// corpus stays untouched. Every vector runs twice: with the D.3.1 changes
// off (noD31), which must pass every earlier check (oracle, D.1/D.2/D.3
// pins, declared divergences) unchanged, and with them on. A vector whose
// output (or, for a mutation, any written file) differs is listed in
// testdata/d3_1/expectations.json and must pass a comparator that proves
// only the approved change differs:
//
//   - read vectors: removing the approved members (resume
//     checkpoint.diagnostic back to null and criticalPath, doctor
//     recoveredPlanFile and the wiped-plan note) gives the D.3.1-off text
//     byte-for-byte, and the additions are restated from the fixture's raw
//     bytes (stale manifest paths, the raw planFile member) or from the
//     inspect critical path;
//   - mutation vectors: the same authorization count and changed-file set;
//     every changed file equals the D.3.1-off file after mapping the
//     whole-second timestamp back to milliseconds and every SHA-256 value
//     to a placeholder, except generated Markdown, which must be the
//     current rendering of the written plan where the D.3.1-off file is the
//     legacy rendering of its plan; the output compares the same way and
//     its hashes match the files on disk.
//
// SHIORI_D31_UPDATE=1 rewrites the expectation hashes (review the diff).

const d31ExpectationsFile = "d3_1/expectations.json"

var (
	d31Once    sync.Once
	d31Loaded  d1File
	d31Mu      sync.Mutex
	d31Updated = map[string]d1Expectation{}
)

func d31Update() bool { return os.Getenv("SHIORI_D31_UPDATE") == "1" }

func d31Expectations(t testing.TB) map[string]d1Expectation {
	d31Once.Do(func() {
		data, err := os.ReadFile(testutil.Testdata(d31ExpectationsFile))
		if err == nil {
			err = json.Unmarshal(data, &d31Loaded)
		}
		if err != nil && !d31Update() {
			t.Fatalf("reading %s: %v", d31ExpectationsFile, err)
		}
		if d31Loaded.Vectors == nil {
			d31Loaded.Vectors = map[string]d1Expectation{}
		}
	})
	return d31Loaded.Vectors
}

const d31Note = "D.3.1 approved design changes (docs/contracts.md §14): oracle vectors whose Go output changes on purpose, with the SHA-256 and UTF-16 length of the pinned Go output (root-normalized; for a refusal, of the error text). Generated by SHIORI_D31_UPDATE=1 go test ./internal/engine ./internal/model; every listed vector also passes a comparator against the same engine with the D.3.1 changes off."

// d31Write rewrites the entries owned by the given prefixes (other
// packages own other prefixes, e.g. internal/model owns markdown/).
func d31Write(t *testing.T, prefixes ...string) {
	if !d31Update() {
		return
	}
	owned := func(id string) bool {
		for _, p := range prefixes {
			if strings.HasPrefix(id, p) {
				return true
			}
		}
		return false
	}
	out := map[string]d1Expectation{}
	var cur d1File
	if data, err := os.ReadFile(testutil.Testdata(d31ExpectationsFile)); err == nil {
		json.Unmarshal(data, &cur)
	}
	for id, x := range cur.Vectors {
		if !owned(id) {
			out[id] = x
		}
	}
	d31Mu.Lock()
	for id, x := range d31Updated {
		if owned(id) {
			out[id] = x
		}
	}
	d31Mu.Unlock()
	data, _ := json.MarshalIndent(d1File{Note: d31Note, Vectors: out}, "", "  ")
	if err := os.MkdirAll(testutil.Testdata("d3_1"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testutil.Testdata(d31ExpectationsFile), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	d31Loaded.Vectors = out
	t.Logf("wrote %s (%d vectors)", d31ExpectationsFile, len(out))
}

func d31Pin(t *testing.T, id, change, normalized string, rawLen int, checkLen bool) string {
	t.Helper()
	if d31Update() {
		d31Mu.Lock()
		d31Updated[id] = d1Expectation{Change: change, OutputSha256: sha(normalized), RawOutputLength: rawLen}
		d31Mu.Unlock()
		return id + ": D.3.1 " + change + " (recorded)"
	}
	x, ok := d31Expectations(t)[id]
	if !ok {
		t.Fatalf("output differs on purpose (D.3.1) but the vector is not listed in %s", d31ExpectationsFile)
	}
	if sha(normalized) != x.OutputSha256 {
		t.Fatalf("D.3.1 pinned output changed: sha %s want %s (SHIORI_D31_UPDATE=1 to re-pin after review)", sha(normalized), x.OutputSha256)
	}
	if checkLen && rawLen != x.RawOutputLength {
		t.Fatalf("D.3.1 raw length %d want %d", rawLen, x.RawOutputLength)
	}
	return id + ": D.3.1 " + x.Change
}

func d31Candidate(t *testing.T, v *vector, text, offText string) bool {
	_, listed := d31Expectations(t)[v.ID]
	return listed || text != offText
}

// ---- read vectors ----

const d31WipedNeedle = "phases: Plan was wiped (workplan_reset mode=wipe)"

func checkD31(t *testing.T, v *vector, root testutil.Root, e *Engine, text, offText string) string {
	t.Helper()
	if text == offText {
		t.Fatalf("listed in %s but identical to the D.3.1-off output; remove the entry", d31ExpectationsFile)
	}
	inv, items, err := d31Inverse(v.Call.Tool, text)
	if err != nil {
		t.Fatalf("D.3.1 comparator: %v", err)
	}
	if inv != offText {
		t.Fatalf("D.3.1 output minus the approved members differs from the D.3.1-off output\n%s", firstDiff(inv, offText))
	}
	if err := d31Restate(root.Path, e, v, text); err != nil {
		t.Fatalf("D.3.1 restatement: %v", err)
	}
	return d31Pin(t, v.ID, "items "+strings.Join(items, ", "), root.Normalize(text), ojson.UTF16Len(text), root.SameLength())
}

// d31Inverse removes exactly the approved D.3.1 read members and names
// the items present.
func d31Inverse(tool, text string) (string, []string, error) {
	parsed, err := ojson.Parse([]byte(text))
	if err != nil {
		return "", nil, err
	}
	v := parsed.Value
	seen := map[string]bool{}
	switch tool {
	case "workplan_resume":
		cp, _ := v.Get("checkpoint")
		if d, _ := cp.Get("diagnostic"); d.Kind() == ojson.String && strings.HasPrefix(d.Str(), "changed: ") {
			seen["3 stale checkpoint diagnostic"] = true
			v = objReplace(v, "checkpoint", objReplace(cp, "diagnostic", ojson.NullValue()))
		}
		if has3(v, "criticalPath") {
			seen["4 resume critical path"] = true
			v = objWithout(v, "criticalPath")
		}
	case "workplan_doctor":
		plans, _ := v.Get("plans")
		var out []ojson.Value
		for _, p := range plans.Elems() {
			if has3(p, "recoveredPlanFile") {
				seen["2b recovered planFile"] = true
				p = objWithout(p, "recoveredPlanFile")
			}
			if w, ok := p.Get("warnings"); ok {
				var keep []string
				for _, x := range w.Elems() {
					if strings.HasPrefix(x.Str(), d31WipedNeedle) {
						seen["5a wiped-plan note"] = true
						continue
					}
					keep = append(keep, x.Str())
				}
				if len(keep) == 0 {
					p = objWithout(p, "warnings")
				} else {
					p = objReplace(p, "warnings", ojson.StringsValue(keep))
				}
			}
			out = append(out, p)
		}
		v = objReplace(v, "plans", ojson.ArrayValue(out))
	default:
		return "", nil, fmt.Errorf("no D.3.1 inverse for %s", tool)
	}
	var items []string
	for k := range seen {
		items = append(items, k)
	}
	sort.Strings(items)
	if !strings.HasPrefix(text, "{\n") {
		return string(ojson.Compact(v)), items, nil // a compact resume packet
	}
	return string(ojson.Pretty(v)), items, nil
}

var d31MoreRe = regexp.MustCompile(` \+(\d+) more$`)

func d31Restate(root string, e *Engine, v *vector, text string) error {
	var doc map[string]any
	if err := json.Unmarshal([]byte(text), &doc); err != nil {
		return err
	}
	var in struct {
		ID string `json:"id"`
	}
	json.Unmarshal(v.Call.Input, &in)
	switch v.Call.Tool {
	case "workplan_resume":
		id := strings.ToLower(in.ID)
		cp, _ := doc["checkpoint"].(map[string]any)
		if d, ok := cp["diagnostic"].(string); ok && strings.HasPrefix(d, "changed: ") {
			if err := restateDiagnostic(root, id, d); err != nil {
				return err
			}
		}
		if c, ok := doc["criticalPath"].(map[string]any); ok {
			insp, err := e.Inspect(InspectInput{ID: in.ID})
			if err != nil {
				return err
			}
			var id map[string]any
			json.Unmarshal(ojson.Pretty(insp), &id)
			full, _ := id["criticalPath"].(map[string]any)
			if full == nil {
				return fmt.Errorf("resume has a critical path but inspect has none")
			}
			steps := asList(full["steps"])
			next := c["nextStep"].(map[string]any)
			first := steps[0].(map[string]any)
			if fmt.Sprint(c["length"]) != fmt.Sprint(full["length"]) || next["phaseId"] != first["phaseId"] || next["stepId"] != first["stepId"] {
				return fmt.Errorf("resume critical path %v, inspect %v", c, full)
			}
		}
	case "workplan_doctor":
		for _, p := range asList(doc["plans"]) {
			e := p.(map[string]any)
			pf, ok := e["recoveredPlanFile"].(string)
			if !ok {
				continue
			}
			raw, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", e["id"].(string)+".json"))
			if err != nil {
				return err
			}
			i := bytes.Index(raw, []byte(`"planFile"`))
			if i < 0 {
				return fmt.Errorf("no planFile member in the raw bytes")
			}
			rest := bytes.TrimLeft(raw[i+len(`"planFile"`):], " \t\r\n")
			rest = bytes.TrimLeft(bytes.TrimPrefix(rest, []byte(":")), " \t\r\n")
			var want string
			if err := json.NewDecoder(bytes.NewReader(rest)).Decode(&want); err != nil {
				return fmt.Errorf("raw planFile: %v", err)
			}
			if strings.TrimPrefix(want, "./") != pf {
				return fmt.Errorf("recoveredPlanFile %q, raw member %q", pf, want)
			}
		}
	}
	return nil
}

// restateDiagnostic checks the compact stale diagnostic against the
// checkpoint manifest and the current plan links, from raw bytes.
func restateDiagnostic(root, id, d string) error {
	var cp struct {
		Manifest []struct {
			Path    string `json:"path"`
			SHA256  string `json:"sha256"`
			Missing bool   `json:"missing"`
		} `json:"manifest"`
	}
	data, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", id+".checkpoint.json"))
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &cp); err != nil {
		return err
	}
	var plan struct {
		PlanFile  string   `json:"planFile"`
		SpecFiles []string `json:"specFiles"`
	}
	pdata, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", id+".json"))
	if err != nil {
		return err
	}
	json.Unmarshal(pdata, &plan)
	now := map[string]bool{".opencode/workplan/" + id + ".json": true, plan.PlanFile: true}
	for _, s := range plan.SpecFiles {
		now[s] = true
	}
	changed := map[string]bool{}
	then := map[string]bool{}
	for _, en := range cp.Manifest {
		then[en.Path] = true
		cur, ok := fileSHA(filepath.Join(root, en.Path))
		if !now[en.Path] || en.Missing != !ok || (ok && cur != en.SHA256) {
			changed[en.Path] = true
		}
	}
	for p := range now {
		if !then[p] {
			changed[p] = true
		}
	}
	body := strings.TrimPrefix(d, "changed: ")
	more := 0
	if m := d31MoreRe.FindStringSubmatch(body); m != nil {
		fmt.Sscan(m[1], &more)
		body = strings.TrimSuffix(body, m[0])
	}
	if len(changed) == 0 {
		if d != "changed: planHash only" {
			return fmt.Errorf("diagnostic %q, restated: planHash only", d)
		}
		return nil
	}
	shown := strings.Split(body, ", ")
	for _, p := range shown {
		if !changed[p] {
			return fmt.Errorf("diagnostic names %s, restated changes %v", p, changed)
		}
	}
	if len(shown) > 3 || len(shown)+more != len(changed) {
		return fmt.Errorf("diagnostic %q lists %d+%d, restated %d", d, len(shown), more, len(changed))
	}
	return nil
}

// ---- mutation vectors ----

var (
	d31Hex64    = regexp.MustCompile(`[0-9a-f]{64}`)
	frozenWhole = frozen.Format("2006-01-02T15:04:05Z")
	frozenMilli = frozen.Format("2006-01-02T15:04:05.000Z")
)

// d31Norm maps the D.3.1 whole-second timestamp back to the millisecond
// form and every SHA-256 value to a placeholder.
func d31Norm(s string) string {
	return d31Hex64.ReplaceAllString(strings.ReplaceAll(s, frozenWhole, frozenMilli), "<sha256>")
}

type d31Run struct {
	root  testutil.Root
	out   Output
	err   error
	auths int
	files map[string][]byte // changed or created files (nil value: deleted)
}

func d31RunMutation(t *testing.T, v *mutationVector, off bool) d31Run {
	t.Helper()
	root := testutil.NewRoot(t, v.Fixture)
	e, err := New(root.Path)
	if err != nil {
		t.Fatal(err)
	}
	e.noD31 = off
	before := snapshotFiles(t, root.Path)
	out, runErr, n := runVectorMutation(t, v, e)
	after := snapshotFiles(t, root.Path)
	r := d31Run{root: root, out: out, err: runErr, auths: n, files: map[string][]byte{}}
	for k, b := range before {
		if a, ok := after[k]; !ok {
			r.files[k] = nil
		} else if a != b {
			r.files[k], _ = os.ReadFile(filepath.Join(root.Path, k))
		}
	}
	for k := range after {
		if _, ok := before[k]; !ok {
			r.files[k], _ = os.ReadFile(filepath.Join(root.Path, k))
		}
	}
	return r
}

// checkD31Mutation compares a mutation vector with the D.3.1 changes on
// and off on fresh copies of its fixture.
func checkD31Mutation(t *testing.T, v *mutationVector) string {
	t.Helper()
	saved := IDSource
	IDSource = nil // generated ids are title slugs in both runs
	defer func() { IDSource = saved }()
	on := d31RunMutation(t, v, false)
	off := d31RunMutation(t, v, true)
	differs := on.auths != off.auths || (on.err == nil) != (off.err == nil)
	if on.err != nil && off.err != nil {
		differs = differs || on.root.Normalize(on.err.Error()) != off.root.Normalize(off.err.Error())
	}
	if on.err == nil && off.err == nil {
		differs = differs || on.root.Normalize(on.out.String()) != off.root.Normalize(off.out.String())
	}
	// A file only one run changed is compared with the other run's
	// unchanged copy (for example a plan whose stored updatedAt already
	// equals the frozen clock in the millisecond form).
	for k := range off.files {
		if _, ok := on.files[k]; !ok {
			on.files[k] = readOrNil(on.root.Path, k)
			differs = true
		}
	}
	for k, b := range on.files {
		ob, ok := off.files[k]
		if !ok {
			ob = readOrNil(off.root.Path, k)
			off.files[k] = ob
			differs = true
		}
		differs = differs || !bytes.Equal(b, ob) || (b == nil) != (ob == nil)
	}
	_, listed := d31Expectations(t)[v.ID]
	if !differs {
		if listed {
			t.Fatalf("listed in %s but identical with the D.3.1 changes off; remove the entry", d31ExpectationsFile)
		}
		return ""
	}
	if on.auths != off.auths {
		t.Fatalf("D.3.1 authorizations %d, D.3.1-off %d", on.auths, off.auths)
	}
	if on.err != nil || off.err != nil {
		if on.err == nil || off.err == nil {
			t.Fatalf("D.3.1 error %v, D.3.1-off error %v", on.err, off.err)
		}
		change := d31ErrorChange(t, v, on, off)
		msg := on.root.Normalize(on.err.Error())
		return d31Pin(t, v.ID, change, msg, ojson.UTF16Len(msg), true)
	}
	// Same changed-file set; each file equal modulo the approved changes.
	var items []string
	addItem := func(s string) {
		for _, x := range items {
			if x == s {
				return
			}
		}
		items = append(items, s)
	}
	for k, b := range on.files {
		ob, ok := off.files[k]
		if !ok || (b == nil) != (ob == nil) {
			t.Fatalf("changed-file sets differ at %s", k)
		}
		if bytes.Equal(b, ob) {
			continue
		}
		if strings.HasSuffix(k, ".md") {
			d31CheckMarkdown(t, v, on, off, k)
			addItem("5b finding rendering")
			continue
		}
		if d31Norm(string(b)) != d31Norm(string(ob)) {
			t.Fatalf("%s differs beyond the timestamp and hashes\n%s", k, firstDiff(d31Norm(string(b)), d31Norm(string(ob))))
		}
		if strings.Contains(string(b), frozenWhole) {
			addItem("5b whole-second timestamps")
		}
	}
	got, want := on.root.Normalize(on.out.String()), off.root.Normalize(off.out.String())
	if d31Norm(got) != d31Norm(want) {
		t.Fatalf("output differs beyond the timestamp and hashes\n%s", firstDiff(d31Norm(got), d31Norm(want)))
	}
	if on.out.Value.Kind() == ojson.Object && has3(on.out.Value, "planHash") && has3(on.out.Value, "workplan") {
		id := strMember(on.out.Value, "workplan", "id")
		hashesMatchDisk(t, on.root.Path, id, on.out)
	}
	if got == want {
		// The output is unchanged; only files differ (pinned by the
		// comparator above, not by an output hash).
		sort.Strings(items)
		return d31Pin(t, v.ID, "items "+strings.Join(items, ", ")+" (files only)", got, ojson.UTF16Len(on.out.String()), false)
	}
	sort.Strings(items)
	return d31Pin(t, v.ID, "items "+strings.Join(items, ", "), got, ojson.UTF16Len(on.out.String()), false)
}

// d31CheckMarkdown: generated Markdown is the current rendering of the
// written plan on, and the legacy rendering of the written plan off, with
// the plans equal after the timestamp mapping.
func d31CheckMarkdown(t *testing.T, v *mutationVector, on, off d31Run, rel string) {
	t.Helper()
	find := func(r d31Run) *model.Plan {
		for k := range r.files {
			if strings.HasPrefix(k, ".opencode/workplan/") && strings.HasSuffix(k, ".json") && !strings.Contains(strings.TrimPrefix(k, ".opencode/workplan/"), "/") &&
				strings.Count(filepath.Base(k), ".") == 1 {
				s, err := snapshot.Load(r.root.Path, strings.TrimSuffix(filepath.Base(k), ".json"), snapshot.DefaultLimits)
				if err == nil && s.Plan.PlanFile == rel {
					return s.Plan
				}
			}
		}
		// The plan JSON may be unchanged (markdown-only reset): find it by link.
		matches, _ := filepath.Glob(filepath.Join(r.root.Path, ".opencode/workplan/*.json"))
		for _, m := range matches {
			base := filepath.Base(m)
			if strings.Count(base, ".") != 1 {
				continue
			}
			s, err := snapshot.Load(r.root.Path, strings.TrimSuffix(base, ".json"), snapshot.DefaultLimits)
			if err == nil && s.Plan.PlanFile == rel {
				return s.Plan
			}
		}
		t.Fatalf("no plan links %s", rel)
		return nil
	}
	pOn, pOff := find(on), find(off)
	if d31Norm(string(pOn.EncodeStored())) != d31Norm(string(pOff.EncodeStored())) {
		t.Fatalf("plans linking %s differ beyond the timestamp", rel)
	}
	cur, err := model.RenderMarkdown(pOn)
	if err != nil {
		t.Fatal(err)
	}
	legacy, err := model.RenderMarkdownLegacy(pOff)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(on.files[rel], cur) || !bytes.Equal(off.files[rel], legacy) {
		t.Fatalf("%s: D.3.1 Markdown is not the current rendering (or D.3.1-off not the legacy rendering)", rel)
	}
}

// d31ErrorChange accepts the approved refusal changes: the unreadable-
// plan repair hint (item 2c) appended to the D.3.1-off message with the
// restated raw state hash, and the step status gate (item 1).
func d31ErrorChange(t *testing.T, v *mutationVector, on, off d31Run) string {
	t.Helper()
	got, want := on.root.Normalize(on.err.Error()), off.root.Normalize(off.err.Error())
	if len(on.files) != 0 {
		t.Fatalf("D.3.1 refusal changed files: %v", on.files)
	}
	var ue *UnreadablePlanError
	if errors.As(on.err, &ue) {
		var in struct {
			ID string `json:"id"`
		}
		json.Unmarshal(v.Call.Input, &in)
		_, sh := restateRawHashes(on.root.Path, strings.ToLower(in.ID))
		if !strings.HasPrefix(got, strings.TrimSuffix(want, ".")+". ") || !strings.Contains(got, "expectedHash="+sh) {
			t.Fatalf("repair hint %q does not extend %q with the raw state hash %s", got, want, sh)
		}
		if ErrorClass(on.err) != ErrorClass(off.err) {
			t.Fatalf("class %s, D.3.1-off %s", ErrorClass(on.err), ErrorClass(off.err))
		}
		return "item 2c repair hint"
	}
	t.Fatalf("D.3.1 error %q differs from D.3.1-off %q", got, want)
	return ""
}

func readOrNil(root, rel string) []byte {
	b, err := os.ReadFile(filepath.Join(root, rel))
	if err != nil {
		return nil
	}
	return b
}
