package engine

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/hoshinoht/shiori/internal/ojson"
	"github.com/hoshinoht/shiori/internal/snapshot"
	"github.com/hoshinoht/shiori/internal/testutil"
)

// D.3 approved design changes (contracts §13, 2026-09-30). The oracle
// corpus stays untouched. Read-path vectors are judged like D.2: the same
// engine with the D.3 additions turned off (noD3) must pass every earlier
// check unchanged, and the D.3 output must (a) turn back into the D.3-off
// output byte-for-byte when the approved members are removed, and (b)
// carry additions that an independent restatement from the fixture's raw
// bytes confirms (raw-byte hashes, stale checkpoint detail, missing step
// markers). Mutation vectors that D.3 changes have dedicated comparators
// below. Every D.3 vector is pinned in testdata/d3/expectations.json.
//
// SHIORI_D3_UPDATE=1 rewrites the expectation hashes (review the diff).

const d3ExpectationsFile = "d3/expectations.json"

var (
	d3Once    sync.Once
	d3Loaded  d1File
	d3Mu      sync.Mutex
	d3Updated = map[string]d1Expectation{}
)

func d3Update() bool { return os.Getenv("SHIORI_D3_UPDATE") == "1" }

func d3Expectations(t testing.TB) map[string]d1Expectation {
	d3Once.Do(func() {
		data, err := os.ReadFile(testutil.Testdata(d3ExpectationsFile))
		if err == nil {
			err = json.Unmarshal(data, &d3Loaded)
		}
		if err != nil && !d3Update() {
			t.Fatalf("reading %s: %v", d3ExpectationsFile, err)
		}
		if d3Loaded.Vectors == nil {
			d3Loaded.Vectors = map[string]d1Expectation{}
		}
	})
	return d3Loaded.Vectors
}

func d3Write(t *testing.T, prefixes ...string) {
	if !d3Update() {
		return
	}
	cur := d3Expectations(t)
	out := map[string]d1Expectation{}
	for id, x := range cur {
		owned := false
		for _, p := range prefixes {
			owned = owned || strings.HasPrefix(id, p)
		}
		if !owned {
			out[id] = x
		}
	}
	d3Mu.Lock()
	for id, x := range d3Updated {
		owned := false
		for _, p := range prefixes {
			owned = owned || strings.HasPrefix(id, p)
		}
		if owned {
			out[id] = x
		}
	}
	d3Mu.Unlock()
	f := d1File{
		Note:    "D.3 approved design changes (docs/contracts.md §13): oracle vectors whose Go output changes on purpose, with the SHA-256 and UTF-16 length of the pinned Go output (root-normalized; for a refusal, of the error text). Generated by SHIORI_D3_UPDATE=1 go test ./internal/engine; read vectors also pass a comparator against the same engine with the D.3 additions off, mutation vectors a dedicated comparator against the oracle.",
		Vectors: out,
	}
	data, _ := json.MarshalIndent(f, "", "  ")
	if err := os.MkdirAll(testutil.Testdata("d3"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testutil.Testdata(d3ExpectationsFile), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	d3Loaded.Vectors = out
	t.Logf("wrote %s (%d vectors)", d3ExpectationsFile, len(out))
}

// d3Pin records (update mode) or checks the pinned output of a D.3 vector.
func d3Pin(t *testing.T, id, change, normalized string, rawLen int, checkLen bool) string {
	t.Helper()
	if d3Update() {
		d3Mu.Lock()
		d3Updated[id] = d1Expectation{Change: change, OutputSha256: sha(normalized), RawOutputLength: rawLen}
		d3Mu.Unlock()
		return id + ": D.3 " + change + " (recorded)"
	}
	x, ok := d3Expectations(t)[id]
	if !ok {
		t.Fatalf("output differs on purpose (D.3) but the vector is not listed in %s", d3ExpectationsFile)
	}
	if sha(normalized) != x.OutputSha256 {
		t.Fatalf("D.3 pinned output changed: sha %s want %s (SHIORI_D3_UPDATE=1 to re-pin after review)", sha(normalized), x.OutputSha256)
	}
	if checkLen && rawLen != x.RawOutputLength {
		t.Fatalf("D.3 raw length %d want %d", rawLen, x.RawOutputLength)
	}
	return id + ": D.3 " + x.Change
}

// d3Change names the D.3 items a read output carries.
func d3Change(tool, text string) string {
	var items []string
	add := func(ok bool, item string) {
		if ok {
			items = append(items, item)
		}
	}
	add(tool == "workplan_list", "5 list issues array")
	add(rawHashesPresent(tool, text), "2 raw-byte hashes")
	add(strings.Contains(text, "stale-markdown"), "3 stale Markdown copy")
	add(strings.Contains(text, d3MarkerNeedle), "4 missing step markers")
	add(strings.Contains(text, msgStale+". "), "5 stale checkpoint detail")
	return "items " + strings.Join(items, ", ")
}

// rawHashesPresent reports an entry that carries raw-byte hashes (an
// unreadable plan: hashes without a workplan summary).
func rawHashesPresent(tool, text string) bool {
	var doc map[string]any
	if json.Unmarshal([]byte(text), &doc) != nil {
		return false
	}
	raw := func(e map[string]any) bool {
		_, w := e["workplan"]
		_, k := e["kind"]
		_, p := e["path"]
		_, h := e["planHash"]
		return h && !w && !k && !p
	}
	switch tool {
	case "workplan_validate":
		return raw(doc)
	case "workplan_doctor":
		for _, p := range asList(doc["plans"]) {
			if raw(p.(map[string]any)) {
				return true
			}
		}
	case "workplan_list":
		for _, p := range asList(doc["workplans"]) {
			if raw(p.(map[string]any)) {
				return true
			}
		}
	}
	return false
}

func d3Candidate(t *testing.T, v *vector, text, offText string) bool {
	_, listed := d3Expectations(t)[v.ID]
	return listed || text != offText
}

func checkD3(t *testing.T, v *vector, root testutil.Root, text, offText string) string {
	t.Helper()
	if text == offText {
		t.Fatalf("listed in %s but identical to the D.3-off output; remove the entry", d3ExpectationsFile)
	}
	inv, err := d3Inverse(v.Call.Tool, text)
	if err != nil {
		t.Fatalf("D.3 comparator: %v", err)
	}
	if inv != offText {
		t.Fatalf("D.3 output minus the approved members differs from the D.3-off output\n%s", firstDiff(inv, offText))
	}
	if err := d3Restate(root.Path, v, text); err != nil {
		t.Fatalf("D.3 restatement: %v", err)
	}
	change := d3Change(v.Call.Tool, text)
	return d3Pin(t, v.ID, change, root.Normalize(text), ojson.UTF16Len(text), root.SameLength())
}

// ---- inverse: remove exactly the approved D.3 members ----

func objWithout(v ojson.Value, keys ...string) ojson.Value {
	drop := map[string]bool{}
	for _, k := range keys {
		drop[k] = true
	}
	var out []ojson.Member
	for _, m := range v.Members() {
		if !drop[m.Key] {
			out = append(out, m)
		}
	}
	return ojson.ObjectValue(out)
}

func objReplace(v ojson.Value, key string, nv ojson.Value) ojson.Value {
	out := append([]ojson.Member(nil), v.Members()...)
	for i := range out {
		if out[i].Key == key {
			out[i].Value = nv
		}
	}
	return ojson.ObjectValue(out)
}

func has3(v ojson.Value, key string) bool { _, ok := v.Get(key); return ok }

const d3MarkerNeedle = "has no step marker (<!-- workplan-step-id: <stepId> -->)"

// withoutMarkerWarning drops the D.3 step-marker warning; the member goes
// when nothing else is left in it.
func withoutMarkerWarning(v ojson.Value) ojson.Value {
	w, ok := v.Get("warnings")
	if !ok {
		return v
	}
	var keep []string
	for _, x := range w.Elems() {
		if !strings.Contains(x.Str(), d3MarkerNeedle) {
			keep = append(keep, x.Str())
		}
	}
	if len(keep) == 0 {
		return objWithout(v, "warnings")
	}
	return objReplace(v, "warnings", ojson.StringsValue(keep))
}

func withoutRawHashes(v ojson.Value) ojson.Value {
	if has3(v, "workplan") || has3(v, "path") || !has3(v, "planHash") || !has3(v, "stateHash") {
		return v
	}
	return objWithout(v, "planHash", "stateHash")
}

func d3Inverse(tool, text string) (string, error) {
	parsed, err := ojson.Parse([]byte(text))
	if err != nil {
		return "", err
	}
	v := parsed.Value
	switch tool {
	case "workplan_validate":
		v = withoutMarkerWarning(withoutRawHashes(v))
	case "workplan_list":
		ws, _ := v.Get("workplans")
		var out []ojson.Value
		for _, p := range ws.Elems() {
			if !has3(p, "kind") {
				issues, _ := p.Get("issues")
				if len(issues.Elems()) != 1 {
					return "", fmt.Errorf("invalid list entry needs exactly one issue: %s", ojson.Compact(p))
				}
				id, _ := p.Get("id")
				valid, _ := p.Get("valid")
				p = ojson.NewObject(3).Set("id", id).Set("valid", valid).Set("issue", issues.Elems()[0]).Value()
			}
			out = append(out, p)
		}
		v = objReplace(v, "workplans", ojson.ArrayValue(out))
	case "workplan_doctor":
		plans, _ := v.Get("plans")
		var out []ojson.Value
		for _, p := range plans.Elems() {
			p = withoutMarkerWarning(withoutRawHashes(p))
			if issues, ok := p.Get("issues"); ok {
				var is []string
				for _, x := range issues.Elems() {
					s := x.Str()
					if pre := "checkpoint: " + msgStale + ". "; strings.HasPrefix(s, pre) {
						s = "checkpoint: " + msgStale
					}
					is = append(is, s)
				}
				p = objReplace(p, "issues", ojson.StringsValue(is))
			}
			out = append(out, p)
		}
		v = objReplace(v, "plans", ojson.ArrayValue(out))
		if strays, ok := v.Get("strayArtifacts"); ok {
			if om, _ := v.Get("omittedStrayArtifacts"); om.NumberLiteral() != "0" {
				return "", fmt.Errorf("stray inverse with omitted entries is not supported")
			}
			var keep []ojson.Value
			for _, s := range strays.Elems() {
				if k, _ := s.Get("kind"); k.Str() != "stale-markdown" {
					keep = append(keep, s)
				}
			}
			var warn []string
			w, _ := v.Get("warnings")
			for _, x := range w.Elems() {
				if !strings.HasPrefix(x.Str(), "Stale Markdown copy ") {
					warn = append(warn, x.Str())
				}
			}
			if len(keep) == 0 {
				v = objWithout(v, "strayArtifacts", "strayArtifactCount", "omittedStrayArtifacts", "warnings")
			} else {
				v = objReplace(v, "strayArtifacts", ojson.ArrayValue(keep))
				v = objReplace(v, "strayArtifactCount", ojson.IntValue(int64(len(keep))))
				v = objReplace(v, "warnings", ojson.StringsValue(warn))
			}
		}
	default:
		return "", fmt.Errorf("no D.3 inverse for %s", tool)
	}
	return string(ojson.Pretty(v)), nil
}

// ---- independent restatement from raw fixture bytes ----

func fileSHA(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:]), true
}

// restateRawHashes recomputes the D.3 raw-byte hashes of an unreadable
// plan straight from the hash contract (contracts §3): the primary JSON,
// plus the three sidecars for the state hash, sorted by path.
func restateRawHashes(root, id string) (string, string) {
	type entry struct{ path, sha string }
	rel := func(suffix string) string { return ".opencode/workplan/" + id + suffix }
	get := func(r string) entry {
		s, ok := fileSHA(filepath.Join(root, r))
		if !ok {
			return entry{r, ""}
		}
		return entry{r, s}
	}
	manifest := func(es []entry) string {
		sort.Slice(es, func(i, j int) bool { return es[i].path < es[j].path })
		var parts []string
		for _, e := range es {
			if e.sha == "" {
				parts = append(parts, fmt.Sprintf(`{"path":%q,"missing":true}`, e.path))
			} else {
				parts = append(parts, fmt.Sprintf(`{"path":%q,"sha256":%q}`, e.path, e.sha))
			}
		}
		return "[" + strings.Join(parts, ",") + "]"
	}
	h := func(version, m string) string {
		sum := sha256.Sum256([]byte(version + "\n" + m + "\n"))
		return hex.EncodeToString(sum[:])
	}
	plan := []entry{get(rel(".json"))}
	state := []entry{get(rel(".json")), get(rel(".checkpoint.json")), get(rel(".dependencies.json")), get(rel(".transaction.json"))}
	return h("workplan-plan-v1", manifest(plan)), h("workplan-state-v1", manifest(state))
}

var staleChanged = regexp.MustCompile(`(\S+) changed \(checkpoint `)

func d3Restate(root string, v *vector, text string) error {
	var doc map[string]any
	if err := json.Unmarshal([]byte(text), &doc); err != nil {
		return err
	}
	var in struct {
		ID string `json:"id"`
	}
	json.Unmarshal(v.Call.Input, &in)
	checkRaw := func(id string, e map[string]any) error {
		ph, _ := e["planHash"].(string)
		sh, _ := e["stateHash"].(string)
		wp, wsh := restateRawHashes(root, id)
		if ph != wp || sh != wsh {
			return fmt.Errorf("%s: raw hashes %s/%s, restated %s/%s", id, ph, sh, wp, wsh)
		}
		return nil
	}
	checkEntry := func(id string, e map[string]any) error {
		if _, ok := e["workplan"]; !ok {
			if _, ok := e["planHash"]; ok {
				if err := checkRaw(id, e); err != nil {
					return err
				}
			}
			return nil
		}
		for _, x := range asList(e["issues"]) {
			s, _ := x.(string)
			if !strings.HasPrefix(s, "checkpoint: "+msgStale+". ") {
				continue
			}
			if err := restateStale(root, id, s); err != nil {
				return err
			}
		}
		for _, x := range asList(e["warnings"]) {
			s, _ := x.(string)
			if strings.Contains(s, d3MarkerNeedle) {
				if err := restateMarkers(root, id, s); err != nil {
					return err
				}
			}
		}
		return nil
	}
	switch v.Call.Tool {
	case "workplan_validate":
		if _, ok := doc["path"]; !ok {
			if _, ok := doc["planHash"]; ok {
				return checkRaw(strings.ToLower(in.ID), doc)
			}
			return nil
		}
		for _, x := range asList(doc["warnings"]) {
			s, _ := x.(string)
			if strings.Contains(s, d3MarkerNeedle) {
				if err := restateMarkers(root, strings.ToLower(in.ID), s); err != nil {
					return err
				}
			}
		}
	case "workplan_doctor":
		for _, p := range asList(doc["plans"]) {
			e := p.(map[string]any)
			if err := checkEntry(e["id"].(string), e); err != nil {
				return err
			}
		}
	case "workplan_list":
		for _, p := range asList(doc["workplans"]) {
			e := p.(map[string]any)
			if _, ok := e["kind"]; ok {
				continue
			}
			if _, ok := e["issue"]; ok {
				return fmt.Errorf("list entry still has the D.1 issue string")
			}
			if _, ok := e["planHash"]; ok {
				if err := checkRaw(e["id"].(string), e); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func asList(x any) []any { l, _ := x.([]any); return l }

// restateStale checks that the stale detail names exactly the checkpoint
// manifest entries whose bytes differ now.
func restateStale(root, id, issue string) error {
	var cp struct {
		Manifest []struct {
			Path    string `json:"path"`
			SHA256  string `json:"sha256"`
			Missing bool   `json:"missing"`
		} `json:"manifest"`
	}
	data, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", id+".checkpoint.json"))
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &cp); err != nil {
		return err
	}
	var want []string
	for _, en := range cp.Manifest {
		now, ok := fileSHA(filepath.Join(root, en.Path))
		if en.Missing != !ok || (ok && now != en.SHA256) {
			want = append(want, en.Path)
		}
	}
	var got []string
	for _, m := range staleChanged.FindAllStringSubmatch(issue, -1) {
		got = append(got, m[1])
	}
	sort.Strings(want)
	sort.Strings(got)
	if !reflect.DeepEqual(got, want) {
		return fmt.Errorf("%s: stale detail names %v, restated %v", id, got, want)
	}
	return nil
}

var markerCount = regexp.MustCompile(`for (\d+) of (\d+) steps: `)

// restateMarkers counts the steps whose marker is absent from the linked
// Markdown, from the raw plan JSON and Markdown text.
func restateMarkers(root, id, warning string) error {
	var plan struct {
		PlanFile string `json:"planFile"`
		Phases   []struct {
			ID    string `json:"id"`
			Steps []struct {
				ID string `json:"id"`
			} `json:"steps"`
		} `json:"phases"`
	}
	data, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", id+".json"))
	if err != nil {
		return err
	}
	if err := json.Unmarshal(data, &plan); err != nil {
		return err
	}
	md, err := os.ReadFile(filepath.Join(root, plan.PlanFile))
	if err != nil {
		return err
	}
	missing, total := 0, 0
	for _, ph := range plan.Phases {
		for _, st := range ph.Steps {
			total++
			if !strings.Contains(string(md), "<!-- workplan-step-id: "+st.ID+" -->") {
				missing++
			}
		}
	}
	m := markerCount.FindStringSubmatch(warning)
	if m == nil || m[1] != fmt.Sprint(missing) || m[2] != fmt.Sprint(total) {
		return fmt.Errorf("%s: marker warning %q, restated %d of %d", id, warning, missing, total)
	}
	return nil
}

// ---- mutation vectors ----

func init() {
	mutationDivergences["mutations/reset-draft"] = mutationDivergence{
		reason: "D.3 item 1: draft reset keeps phases/steps/findings/notes and resets every status to draft; the output differs only in the kept counts and the hashes",
		run:    checkResetDraftD3,
	}
	mutationDivergences["mutations/reset-draft-preserve-notes"] = mutationDivergence{
		reason: "D.3 item 1: draft reset keeps phases/steps/findings/notes and resets every status to draft; the output differs only in the kept counts and the hashes",
		run:    checkResetDraftD3,
	}
	mutationDivergences["mutations/create-generated-ids"] = mutationDivergence{
		reason: "D.3 item 5: generated ids are title slugs; the plan and Markdown equal the oracle's after substituting the ids, the output differs only in the hashes",
		run:    checkGeneratedIDsD3,
	}
	mutationDivergences["mutations/create-new-full"] = mutationDivergence{
		reason: "D.3 item 5: a specFiles link to a missing file is refused before authorization; with the file present the result is the oracle's (files byte-identical, hashes bind the spec)",
		run:    checkSpecRefusalD3,
	}
	mutationDivergences["mutations/update-recovery-resume"] = mutationDivergence{
		reason: "D.3 item 6: recovery also removes the interrupted transaction's leftover staging file; every other change is the oracle's",
		run:    checkRecoveryStagingD3,
	}
	mutationDivergences["mutations/update-recovery-rollback"] = mutationDivergence{
		reason: "D.3 item 6: recovery also removes the interrupted transaction's leftover staging file; every other change is the oracle's",
		run:    checkRecoveryStagingD3,
	}
}

func decodeJSONFile(t *testing.T, path string) map[string]any {
	t.Helper()
	var m map[string]any
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	d := json.NewDecoder(strings.NewReader(string(data)))
	d.UseNumber()
	if err := d.Decode(&m); err != nil {
		t.Fatal(err)
	}
	return m
}

// outputExcept compares a mutation output with the oracle output after
// deleting the named workplan-summary members and top-level members.
func outputExcept(t *testing.T, v *mutationVector, got string, summary []string, top []string) {
	t.Helper()
	g, err := decodeAny(got)
	if err != nil {
		t.Fatal(err)
	}
	var w any
	d := json.NewDecoder(strings.NewReader(string(v.Expect.Output)))
	d.UseNumber()
	d.Decode(&w)
	gm, wm := g.(map[string]any), w.(map[string]any)
	for _, m := range []map[string]any{gm, wm} {
		for _, k := range top {
			delete(m, k)
		}
		if s, ok := m["workplan"].(map[string]any); ok {
			for _, k := range summary {
				delete(s, k)
			}
		}
	}
	if !reflect.DeepEqual(gm, wm) {
		gb, _ := json.Marshal(gm)
		wb, _ := json.Marshal(wm)
		t.Fatalf("output differs beyond the D.3 members\n got %s\nwant %s", gb, wb)
	}
}

func runVectorMutation(t *testing.T, v *mutationVector, e *Engine) (Output, error, int) {
	input, err := ojson.Parse(v.Call.Input)
	if err != nil {
		t.Fatal(err)
	}
	auth := &countingAuth{}
	out, runErr := runMutation(context.Background(), e, v.Call.Tool, input.Value, auth)
	return out, runErr, auth.n
}

// hashesMatchDisk checks the output hashes against the committed files.
func hashesMatchDisk(t *testing.T, root, id string, out Output) {
	t.Helper()
	s, err := snapshot.Load(root, id, snapshot.DefaultLimits)
	if err != nil {
		t.Fatal(err)
	}
	ph, _ := out.Value.Get("planHash")
	sh, _ := out.Value.Get("stateHash")
	if ph.Str() != s.PlanHash || sh.Str() != s.StateHash {
		t.Fatalf("output hashes %s/%s, disk %s/%s", ph.Str(), sh.Str(), s.PlanHash, s.StateHash)
	}
}

func checkResetDraftD3(t *testing.T, v *mutationVector, root testutil.Root, e *Engine) {
	dir := filepath.Join(root.Path, ".opencode", "workplan")
	var in struct {
		ID string `json:"id"`
	}
	json.Unmarshal(v.Call.Input, &in)
	before := decodeJSONFile(t, filepath.Join(dir, in.ID+".json"))
	beforeFiles := snapshotFiles(t, root.Path)
	out, err, n := runVectorMutation(t, v, e)
	if err != nil {
		t.Fatal(err)
	}
	if n != 1 {
		t.Fatalf("authorizations %d, want 1", n)
	}
	outputExcept(t, v, root.Normalize(out.String()), []string{"phaseCount", "stepCount", "openFindingCount"}, []string{"planHash", "stateHash", "checkpointRemoved"})
	// Restate the expected JSON: the before document with every status
	// set to draft and updatedAt at the frozen clock.
	want := before
	want["status"] = "draft"
	want["updatedAt"] = frozen.Format("2006-01-02T15:04:05.000Z")
	phases := asList(want["phases"])
	steps, open := 0, 0
	for _, ph := range phases {
		pm := ph.(map[string]any)
		pm["status"] = "draft"
		for _, st := range asList(pm["steps"]) {
			st.(map[string]any)["status"] = "draft"
			steps++
		}
	}
	for _, f := range asList(want["reviewFindings"]) {
		if f.(map[string]any)["status"] != "resolved" {
			open++
		}
	}
	after := decodeJSONFile(t, filepath.Join(dir, in.ID+".json"))
	if !reflect.DeepEqual(after, want) {
		t.Fatalf("draft reset JSON is not the status-only reset of the stored plan")
	}
	wp, _ := out.Value.Get("workplan")
	for k, n := range map[string]int{"phaseCount": len(phases), "stepCount": steps, "openFindingCount": open} {
		if x, _ := wp.Get(k); x.NumberLiteral() != fmt.Sprint(n) {
			t.Fatalf("%s %s, restated %d", k, x.NumberLiteral(), n)
		}
	}
	hashesMatchDisk(t, root.Path, in.ID, out)
	// The Markdown was generated, so it follows the JSON; the checkpoint
	// (if any) is removed; nothing else changes.
	s, _ := snapshot.Load(root.Path, in.ID, snapshot.DefaultLimits)
	if gen, _ := e.generatedMarkdown(s); !gen {
		t.Fatal("generated Markdown was not regenerated")
	}
	afterFiles := snapshotFiles(t, root.Path)
	allowed := map[string]bool{".opencode/workplan/" + in.ID + ".json": true, s.Plan.PlanFile: true, ".opencode/workplan/" + in.ID + ".checkpoint.json": true}
	for k, b := range beforeFiles {
		if a, ok := afterFiles[k]; (!ok || a != b) && !allowed[k] {
			t.Fatalf("unexpected change %s", k)
		}
	}
	if _, ok := afterFiles[".opencode/workplan/"+in.ID+".checkpoint.json"]; ok {
		t.Fatal("checkpoint not removed")
	}
	t.Log(d3Pin(t, v.ID, "item 1 draft reset keeps structure", root.Normalize(out.String()), ojson.UTF16Len(out.String()), false))
}

func checkGeneratedIDsD3(t *testing.T, v *mutationVector, root testutil.Root, e *Engine) {
	IDSource = nil
	out, err, n := runVectorMutation(t, v, e)
	if err != nil || n != 1 {
		t.Fatalf("err %v, authorizations %d", err, n)
	}
	outputExcept(t, v, root.Normalize(out.String()), nil, []string{"planHash", "stateHash"})
	subst := strings.NewReplacer(seededIDs[v.ID][0], "p", seededIDs[v.ID][1], "s")
	for rel, cf := range map[string]string{".opencode/workplan/gen.json": "gen.json", ".opencode/workplan/gen.md": "gen.md"} {
		oracle, err := os.ReadFile(testutil.Testdata("vectors", "mutations", "create-generated-ids.after", ".opencode", "workplan", cf))
		if err != nil {
			t.Fatal(err)
		}
		got, err := os.ReadFile(filepath.Join(root.Path, rel))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != subst.Replace(string(oracle)) {
			t.Fatalf("%s differs from the oracle beyond the generated ids", rel)
		}
	}
	hashesMatchDisk(t, root.Path, "gen", out)
	t.Log(d3Pin(t, v.ID, "item 5 title-slug ids", root.Normalize(out.String()), ojson.UTF16Len(out.String()), false))
}

func checkSpecRefusalD3(t *testing.T, v *mutationVector, root testutil.Root, e *Engine) {
	before := testutil.Fingerprint(t, root.Path)
	_, err, n := runVectorMutation(t, v, e)
	want := "specFiles.0: Linked spec file does not exist: docs/x.md. Create the file first, or leave it out of the list."
	if err == nil || err.Error() != want || n != 0 {
		t.Fatalf("err %v (authorizations %d), want %q before authorization", err, n, want)
	}
	if ErrorClass(err) != "invalid_input" {
		t.Fatalf("class %s", ErrorClass(err))
	}
	if d := testutil.DiffFingerprints(before, testutil.Fingerprint(t, root.Path)); len(d) > 0 {
		t.Fatalf("refusal changed files: %v", d)
	}
	// With the spec present, every changed file is the oracle's.
	if err := os.MkdirAll(filepath.Join(root.Path, "docs"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root.Path, "docs", "x.md"), []byte("# x\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	b := snapshotFiles(t, root.Path)
	out, err, n := runVectorMutation(t, v, e)
	if err != nil || n != 1 {
		t.Fatalf("with the spec present: err %v, authorizations %d", err, n)
	}
	outputExcept(t, v, root.Normalize(out.String()), nil, []string{"planHash", "stateHash"})
	checkChanged(t, v, b, snapshotFiles(t, root.Path))
	t.Log(d3Pin(t, v.ID, "item 5 missing spec refused", want, ojson.UTF16Len(want), true))
}

func checkRecoveryStagingD3(t *testing.T, v *mutationVector, root testutil.Root, e *Engine) {
	jpath := filepath.Join(root.Path, ".opencode/workplan/tx-plan.transaction.json")
	var j struct {
		TransactionID string `json:"transactionId"`
	}
	data, err := os.ReadFile(jpath)
	if err != nil {
		t.Fatal(err)
	}
	json.Unmarshal(data, &j)
	matches, _ := filepath.Glob(filepath.Join(root.Path, ".opencode/workplan", "*."+j.TransactionID+".*.stage"))
	if len(matches) == 0 {
		t.Fatal("fixture has no leftover staging file of the interrupted transaction")
	}
	extra := map[string]bool{}
	for _, m := range matches {
		rel, _ := filepath.Rel(root.Path, m)
		extra[filepath.ToSlash(rel)] = true
	}
	withStage := *v
	withStage.ChangedFiles = map[string]struct {
		SHA256  string `json:"sha256"`
		Deleted bool   `json:"deleted"`
	}{}
	for k, x := range v.ChangedFiles {
		withStage.ChangedFiles[k] = x
	}
	for k := range extra {
		withStage.ChangedFiles[k] = struct {
			SHA256  string `json:"sha256"`
			Deleted bool   `json:"deleted"`
		}{Deleted: true}
	}
	checkMutationVector(t, &withStage, root, e)
}
