package engine

import (
	"encoding/json"
	"os"
	"strings"
	"sync"
	"testing"

	"github.com/hoshinoht/shiori/internal/ojson"
	"github.com/hoshinoht/shiori/internal/testutil"
)

// D.4.1 approved design change (contracts §16, 2026-10-01): expectedHash
// guidance. The oracle corpus stays untouched. The native missing
// expectedHash refusal and the stale expectedHash refusal keep their
// reference text and append guidance (nativeHashGuidance,
// staleHashGuidance). A vector whose error text differs is listed in
// testdata/d4_1/expectations.json (SHA-256 and UTF-16 length of the
// root-normalized error text) and must pass the comparator: removing each
// guidance suffix gives the oracle text byte-for-byte, the guidance
// follows its reference sentence, and it echoes no hash.
//
// SHIORI_D41_UPDATE=1 rewrites the expectation hashes (review the diff).

const d41ExpectationsFile = "d4_1/expectations.json"

var (
	d41Once    sync.Once
	d41Loaded  d1File
	d41Mu      sync.Mutex
	d41Updated = map[string]d1Expectation{}
)

func d41Update() bool { return os.Getenv("SHIORI_D41_UPDATE") == "1" }

func d41Expectations(t testing.TB) map[string]d1Expectation {
	d41Once.Do(func() {
		data, err := os.ReadFile(testutil.Testdata(d41ExpectationsFile))
		if err == nil {
			err = json.Unmarshal(data, &d41Loaded)
		}
		if err != nil && !d41Update() {
			t.Fatalf("reading %s: %v", d41ExpectationsFile, err)
		}
		if d41Loaded.Vectors == nil {
			d41Loaded.Vectors = map[string]d1Expectation{}
		}
	})
	return d41Loaded.Vectors
}

const d41Note = "D.4.1 approved design change (docs/contracts.md §16, 2026-10-01): oracle vectors whose Go error text changes on purpose (expectedHash guidance appended to the native missing-hash and the stale-hash refusals), with the SHA-256 and UTF-16 length of the pinned error text (root-normalized). Generated by SHIORI_D41_UPDATE=1 go test ./internal/engine -run 'TestMutationInputVectors|TestMutationVectors'; every listed vector also passes a comparator: removing the guidance gives the oracle text byte-for-byte."

// d41Write rewrites the entries owned by the given prefixes.
func d41Write(t *testing.T, prefixes ...string) {
	if !d41Update() {
		return
	}
	owned := func(id string) bool {
		for _, p := range prefixes {
			if strings.HasPrefix(id, p) {
				return true
			}
		}
		return false
	}
	out := map[string]d1Expectation{}
	var cur d1File
	if data, err := os.ReadFile(testutil.Testdata(d41ExpectationsFile)); err == nil {
		json.Unmarshal(data, &cur)
	}
	for id, x := range cur.Vectors {
		if !owned(id) {
			out[id] = x
		}
	}
	d41Mu.Lock()
	for id, x := range d41Updated {
		if owned(id) {
			out[id] = x
		}
	}
	d41Mu.Unlock()
	data, _ := json.MarshalIndent(d1File{Note: d41Note, Vectors: out}, "", "  ")
	if err := os.MkdirAll(testutil.Testdata("d4_1"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testutil.Testdata(d41ExpectationsFile), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	d41Loaded.Vectors = out
	t.Logf("wrote %s (%d vectors)", d41ExpectationsFile, len(out))
}

// d41Compare proves that got differs from the oracle text want only by the
// approved guidance: each suffix directly follows its reference sentence,
// and removing every suffix gives want byte-for-byte.
func d41Compare(got, want string) (string, bool) {
	if got == want {
		return "", false
	}
	var changes []string
	if strings.Contains(got, nativeHashGuidance) {
		if strings.Count(got, "require the current stateHash"+nativeHashGuidance) != strings.Count(got, nativeHashGuidance) {
			return "", false
		}
		changes = append(changes, "native expectedHash guidance")
	}
	if strings.Contains(got, staleHashGuidance) {
		if !strings.HasSuffix(got, "Reread the plan and recompute the mutation."+staleHashGuidance) {
			return "", false
		}
		changes = append(changes, "stale expectedHash guidance")
	}
	stripped := strings.ReplaceAll(strings.ReplaceAll(got, nativeHashGuidance, ""), staleHashGuidance, "")
	if stripped != want || len(changes) == 0 {
		return "", false
	}
	return strings.Join(changes, ", "), true
}

// checkD41Text compares an error text with the oracle's under the D.4.1
// comparator and the pin; it fails the test when neither matches.
func checkD41Text(t *testing.T, id, got, want string) string {
	t.Helper()
	if got == want {
		if _, listed := d41Expectations(t)[id]; listed && !d41Update() {
			t.Fatalf("listed in %s but identical to the oracle text; remove the entry", d41ExpectationsFile)
		}
		return ""
	}
	change, ok := d41Compare(got, want)
	if !ok {
		t.Fatalf("error\n got %q\nwant %q", got, want)
	}
	for _, h := range []string{nativeHashGuidance, staleHashGuidance} {
		if d31Hex64.MatchString(h) {
			t.Fatalf("D.4.1 guidance echoes a hash: %q", h)
		}
	}
	if d41Update() {
		d41Mu.Lock()
		d41Updated[id] = d1Expectation{Change: change, OutputSha256: sha(got), RawOutputLength: ojson.UTF16Len(got)}
		d41Mu.Unlock()
		return id + ": D.4.1 " + change + " (recorded)"
	}
	x, ok := d41Expectations(t)[id]
	if !ok {
		t.Fatalf("error text differs on purpose (D.4.1) but the vector is not listed in %s", d41ExpectationsFile)
	}
	if sha(got) != x.OutputSha256 || ojson.UTF16Len(got) != x.RawOutputLength {
		t.Fatalf("D.4.1 pinned error text changed: sha %s want %s (SHIORI_D41_UPDATE=1 to re-pin after review)", sha(got), x.OutputSha256)
	}
	return id + ": D.4.1 " + x.Change
}

// TestD41Guidance checks the guidance on every native existing-state
// writer and on a stale hash through the engine.
func TestD41Guidance(t *testing.T) {
	lead := "Native existing-state writes require the current stateHash"
	cases := map[string]string{
		"update":     `{"id":"x","title":"t"}`,
		"patch":      `{"id":"x","patchText":"p"}`,
		"reset":      `{"id":"x","mode":"draft"}`,
		"checkpoint": `{"id":"x","summary":"s","nextAction":"n"}`,
		"compact":    `{"id":"x","mode":"apply","archiveReason":"r","confirmation":"ARCHIVE_SELECTED_HISTORY","previewToken":"t"}`,
		"create":     `{"id":"x","goal":"g","overwrite":true}`,
	}
	for tool, in := range cases {
		v, err := ojson.Parse([]byte(in))
		if err != nil {
			t.Fatal(err)
		}
		_, err = ParseMutationInput(tool, v.Value, SurfaceNative)
		if err == nil {
			t.Fatalf("%s: accepted without expectedHash", tool)
		}
		want := "expectedHash: " + lead + nativeHashGuidance
		if !strings.Contains(err.Error(), want) || ErrorClass(err) != "invalid_input" {
			t.Fatalf("%s: %v (class %s), want %q", tool, err, ErrorClass(err), want)
		}
		if d31Hex64.MatchString(err.Error()) {
			t.Fatalf("%s: message echoes a hash: %v", tool, err)
		}
		// The core surface keeps its reference text.
		if _, err := ParseMutationInput(tool, v.Value, SurfaceCore); err != nil && strings.Contains(err.Error(), nativeHashGuidance) {
			t.Fatalf("%s: core surface got the native guidance: %v", tool, err)
		}
	}
	se := &StaleHashError{Current: strings.Repeat("a", 64)}
	if msg := se.Error(); !strings.HasPrefix(msg, "Stale expectedHash; current stateHash is "+se.Current+". Reread the plan and recompute the mutation. ") ||
		strings.Count(msg, se.Current) != 1 || !strings.Contains(msg, "workplan_resume") || ErrorClass(se) != "stale_state" {
		t.Fatalf("stale message %q class %s", msg, ErrorClass(se))
	}
}
