package engine

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"sync"
	"testing"

	"github.com/hoshinoht/shiori/internal/ojson"
	"github.com/hoshinoht/shiori/internal/testutil"
)

// D.4.3 approved design changes (contracts §18, 2026-10-01): withheld
// checkpoint fields named in resume, checkpoint write warnings, the
// withheld-placeholder refusal and merge mode. The oracle corpus stays
// untouched. Every tools/resume/paging vector runs with the D.4.3
// additions off (noD43), which must pass every earlier check unchanged,
// and with them on. A vector whose output differs must be listed in
// testdata/d4_3/expectations.json and pass a comparator:
//
//   - resume: checkpoint.withheld equals the list restated from the raw
//     checkpoint file, the instruction is the D.1 stale text followed by
//     the D.4.3 sentence (naming the checkpoint file and merge=true), and
//     removing withheld and restoring the D.1 instruction gives the
//     D.4.3-off text byte-for-byte (the same budget level);
//   - checkpoint writes (mutation vectors): the only difference is the
//     result's warnings member, restated from the fixture's stored
//     checkpoint and the vector input; files and authorizations are equal.
//
// SHIORI_D43_UPDATE=1 rewrites the expectation hashes (review the diff).

const d43ExpectationsFile = "d4_3/expectations.json"

var (
	d43Once    sync.Once
	d43Loaded  d1File
	d43Mu      sync.Mutex
	d43Updated = map[string]d1Expectation{}
)

func d43Update() bool { return os.Getenv("SHIORI_D43_UPDATE") == "1" }

func d43Expectations(t testing.TB) map[string]d1Expectation {
	d43Once.Do(func() {
		data, err := os.ReadFile(testutil.Testdata(d43ExpectationsFile))
		if err == nil {
			err = json.Unmarshal(data, &d43Loaded)
		}
		if err != nil && !d43Update() {
			t.Fatalf("reading %s: %v", d43ExpectationsFile, err)
		}
		if d43Loaded.Vectors == nil {
			d43Loaded.Vectors = map[string]d1Expectation{}
		}
	})
	return d43Loaded.Vectors
}

const d43Note = "D.4.3 approved design changes (docs/contracts.md §18, 2026-10-01): oracle vectors whose Go output changes on purpose (resume names the withheld fields of a stale or legacy checkpoint and points at the checkpoint file and merge=true; a checkpoint write that drops stored list entries returns warnings), with the SHA-256 and UTF-16 length of the pinned Go output (root-normalized). Generated by SHIORI_D43_UPDATE=1 go test ./internal/engine -run 'TestCorpusParity|TestMutationVectors'; every listed vector also passes a comparator against the same engine with the D.4.3 additions off."

// d43Write rewrites the entries owned by the given prefixes.
func d43Write(t *testing.T, prefixes ...string) {
	if !d43Update() {
		return
	}
	owned := func(id string) bool {
		for _, p := range prefixes {
			if strings.HasPrefix(id, p) {
				return true
			}
		}
		return false
	}
	out := map[string]d1Expectation{}
	var cur d1File
	if data, err := os.ReadFile(testutil.Testdata(d43ExpectationsFile)); err == nil {
		json.Unmarshal(data, &cur)
	}
	for id, x := range cur.Vectors {
		if !owned(id) {
			out[id] = x
		}
	}
	d43Mu.Lock()
	for id, x := range d43Updated {
		if owned(id) {
			out[id] = x
		}
	}
	d43Mu.Unlock()
	data, _ := json.MarshalIndent(d1File{Note: d43Note, Vectors: out}, "", "  ")
	if err := os.MkdirAll(testutil.Testdata("d4_3"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testutil.Testdata(d43ExpectationsFile), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	d43Loaded.Vectors = out
	t.Logf("wrote %s (%d vectors)", d43ExpectationsFile, len(out))
}

func d43Candidate(t *testing.T, v *vector, text, offText string) bool {
	_, listed := d43Expectations(t)[v.ID]
	return listed || text != offText
}

// d43Pin checks (or records) the pinned output of a listed vector.
func d43Pin(t *testing.T, id, change, normalized string, rawLen int, sameLength bool) string {
	t.Helper()
	if d43Update() {
		d43Mu.Lock()
		d43Updated[id] = d1Expectation{Change: change, OutputSha256: sha(normalized), RawOutputLength: rawLen}
		d43Mu.Unlock()
		return id + ": D.4.3 " + change + " (recorded)"
	}
	x, ok := d43Expectations(t)[id]
	if !ok {
		t.Fatalf("output differs on purpose (D.4.3) but the vector is not listed in %s", d43ExpectationsFile)
	}
	if x.Change != change {
		t.Fatalf("D.4.3 change %q, pinned %q", change, x.Change)
	}
	if sha(normalized) != x.OutputSha256 {
		t.Fatalf("D.4.3 pinned output changed: sha %s want %s (SHIORI_D43_UPDATE=1 to re-pin after review)", sha(normalized), x.OutputSha256)
	}
	if sameLength && rawLen != x.RawOutputLength {
		t.Fatalf("D.4.3 raw length %d want %d", rawLen, x.RawOutputLength)
	}
	return id + ": D.4.3 " + x.Change
}

func checkD43(t *testing.T, v *vector, root testutil.Root, input ojson.Value, text, offText string) string {
	t.Helper()
	if text == offText {
		t.Fatalf("listed in %s but identical to the D.4.3-off output; remove the entry", d43ExpectationsFile)
	}
	if v.Call.Tool != "workplan_resume" {
		t.Fatalf("no D.4.3 read-path change for %s", v.Call.Tool)
	}
	idv, _ := input.Get("id")
	if err := d43CompareResume(root.Path, idv.Str(), text, offText); err != nil {
		t.Fatalf("D.4.3 comparator: %v", err)
	}
	return d43Pin(t, v.ID, "withheld checkpoint fields", root.Normalize(text), ojson.UTF16Len(text), root.SameLength())
}

// d43RestateWithheld is the test's own statement of contracts §18 item 1:
// summary and nextAction always, then guardrails, references and
// recentValidation when the stored checkpoint has entries.
func d43RestateWithheld(root, id string) ([]string, error) {
	data, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", id+".checkpoint.json"))
	if err != nil {
		return nil, err
	}
	var cp map[string]any
	if err := json.Unmarshal(data, &cp); err != nil {
		return nil, err
	}
	out := []string{"summary", "nextAction"}
	for _, k := range []string{"guardrails", "references", "recentValidation"} {
		if l, _ := cp[k].([]any); len(l) > 0 {
			out = append(out, k)
		}
	}
	return out, nil
}

// d43CompareResume checks a resume packet against the D.4.3-off packet.
func d43CompareResume(root, id, text, offText string) error {
	parsed, err := ojson.Parse([]byte(text))
	if err != nil {
		return err
	}
	v := parsed.Value
	cp, _ := v.Get("checkpoint")
	w, ok := cp.Get("withheld")
	if !ok {
		return fmt.Errorf("resume output differs without checkpoint.withheld")
	}
	var got []string
	for _, x := range w.Elems() {
		got = append(got, x.Str())
	}
	want, err := d43RestateWithheld(root, id)
	if err != nil {
		return err
	}
	if !reflect.DeepEqual(got, want) {
		return fmt.Errorf("withheld %v, restated %v", got, want)
	}
	ins, _ := v.Get("instruction")
	rel := ".opencode/workplan/" + id + ".checkpoint.json"
	if !strings.HasPrefix(ins.Str(), instructionStale+" ") || !strings.Contains(ins.Str(), rel) ||
		!strings.Contains(ins.Str(), "via workplan_checkpoint merge=true") || !strings.Contains(ins.Str(), "(workplan_read omits it)") {
		return fmt.Errorf("instruction %q", ins.Str())
	}
	v = objReplace(v, "checkpoint", objWithout(cp, "withheld"))
	v = objReplace(v, "instruction", ojson.StringValue(instructionStale))
	inv := string(ojson.Pretty(v))
	if !strings.HasPrefix(text, "{\n") {
		inv = string(ojson.Compact(v))
	}
	if inv != offText {
		return fmt.Errorf("output minus withheld/instruction differs from the D.4.3-off output (budget level changed?)\n%s", firstDiff(inv, offText))
	}
	return nil
}

// d43Run is one mutation vector run on a fresh fixture copy.
func d43RunMutation(t *testing.T, v *mutationVector, off bool) d31Run {
	t.Helper()
	root := testutil.NewRoot(t, v.Fixture)
	e, err := New(root.Path)
	if err != nil {
		t.Fatal(err)
	}
	e.noD43 = off
	before := snapshotFiles(t, root.Path)
	out, runErr, n := runVectorMutation(t, v, e)
	after := snapshotFiles(t, root.Path)
	r := d31Run{root: root, out: out, err: runErr, auths: n, files: map[string][]byte{}}
	for k, b := range before {
		if a, ok := after[k]; !ok {
			r.files[k] = nil
		} else if a != b {
			r.files[k], _ = os.ReadFile(filepath.Join(root.Path, k))
		}
	}
	for k := range after {
		if _, ok := before[k]; !ok {
			r.files[k], _ = os.ReadFile(filepath.Join(root.Path, k))
		}
	}
	return r
}

var (
	d43MutationMu    sync.Mutex
	d43MutationNotes []string
)

// checkD43Mutation compares a mutation vector with the D.4.3 additions on
// and off (all earlier changes on in both runs).
func checkD43Mutation(t *testing.T, v *mutationVector) string {
	t.Helper()
	saved := IDSource
	IDSource = nil
	defer func() { IDSource = saved }()
	on := d43RunMutation(t, v, false)
	off := d43RunMutation(t, v, true)
	if on.auths != off.auths || (on.err == nil) != (off.err == nil) {
		t.Fatalf("D.4.3 authorizations/errors differ: %d/%v vs %d/%v", on.auths, on.err, off.auths, off.err)
	}
	if on.err != nil {
		if on.root.Normalize(on.err.Error()) != off.root.Normalize(off.err.Error()) {
			t.Fatalf("D.4.3 error text differs: %v vs %v", on.err, off.err)
		}
		if _, listed := d43Expectations(t)[v.ID]; listed && !d43Update() {
			t.Fatalf("listed in %s but identical with D.4.3 off; remove the entry", d43ExpectationsFile)
		}
		return ""
	}
	keys := func(m map[string][]byte) []string {
		var out []string
		for k := range m {
			out = append(out, k)
		}
		sort.Strings(out)
		return out
	}
	if !reflect.DeepEqual(keys(on.files), keys(off.files)) {
		t.Fatalf("D.4.3 changed-file sets differ: %v vs %v", keys(on.files), keys(off.files))
	}
	for k, b := range on.files {
		if !bytes.Equal(b, off.files[k]) {
			t.Fatalf("D.4.3 changed %s", k)
		}
	}
	got, want := on.root.Normalize(on.out.String()), off.root.Normalize(off.out.String())
	_, listed := d43Expectations(t)[v.ID]
	if got == want {
		if listed && !d43Update() {
			t.Fatalf("listed in %s but identical with D.4.3 off; remove the entry", d43ExpectationsFile)
		}
		return ""
	}
	if v.Call.Tool != "workplan_checkpoint" {
		t.Fatalf("D.4.3 changed a %s result", v.Call.Tool)
	}
	ws, ok := on.out.Value.Get("warnings")
	if !ok {
		t.Fatalf("D.4.3 checkpoint result differs without warnings")
	}
	inv := string(ojson.Pretty(objWithout(on.out.Value, "warnings")))
	if on.root.Normalize(inv) != want {
		t.Fatalf("D.4.3 result minus warnings differs\n%s", firstDiff(on.root.Normalize(inv), want))
	}
	restated := d43RestateWarnings(t, v)
	var gotW []string
	for _, x := range ws.Elems() {
		gotW = append(gotW, x.Str())
	}
	if !reflect.DeepEqual(gotW, restated) {
		t.Fatalf("warnings %q, restated %q", gotW, restated)
	}
	return d43Pin(t, v.ID, "checkpoint drop warnings", got, ojson.UTF16Len(on.out.String()), true)
}

// d43RestateWarnings restates contracts §18 item 2 from the fixture's
// stored checkpoint and the vector input (no merge in the corpus): each
// list whose stored entries are not all in the new list, in the order
// guardrails, references, recentValidation, blockers.
func d43RestateWarnings(t *testing.T, v *mutationVector) []string {
	t.Helper()
	var in map[string]any
	json.Unmarshal(v.Call.Input, &in)
	id, _ := in["id"].(string)
	data, err := os.ReadFile(testutil.Testdata("fixtures", v.Fixture, ".opencode/workplan", id+".checkpoint.json"))
	if err != nil {
		t.Fatalf("restating warnings: %v", err)
	}
	var cp map[string]any
	if err := json.Unmarshal(data, &cp); err != nil {
		t.Fatal(err)
	}
	strs := func(x any) []string {
		var out []string
		seen := map[string]bool{}
		l, _ := x.([]any)
		for _, e := range l {
			s := strings.TrimSpace(e.(string))
			if s != "" && !seen[s] {
				seen[s] = true
				out = append(out, s)
			}
		}
		return out
	}
	var out []string
	for _, k := range []string{"guardrails", "references", "recentValidation", "blockers"} {
		var before []string // the stored list as stored
		if l, ok := cp[k].([]any); ok {
			for _, e := range l {
				before = append(before, e.(string))
			}
		}
		now := strs(in[k])
		kept := map[string]bool{}
		for _, x := range now {
			kept[x] = true
		}
		n := 0
		for _, x := range before {
			if !kept[x] {
				n++
			}
		}
		if n == 0 {
			continue
		}
		noun := "entries"
		if n == 1 {
			noun = "entry"
		}
		out = append(out, fmt.Sprintf("%s: %d → %d (%d previous %s not kept; merge=true keeps omitted fields)", k, len(before), len(now), n, noun))
	}
	return out
}
