package engine

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"testing"

	"github.com/hoshinoht/shiori/internal/ojson"
	"github.com/hoshinoht/shiori/internal/testutil"
)

// D.4 approved design changes (contracts §15, 2026-09-30): the compaction
// advisor (P2) and note rollover (P3). The oracle corpus stays untouched.
// Every tools/resume/paging vector runs twice: with the D.4 advice off
// (noD4), which must pass every earlier check (oracle, D.1–D.3.1 pins,
// declared divergences) unchanged, and with it on. A vector whose output
// differs must be listed in testdata/d4/expectations.json and pass a
// comparator: removing compactionRecommended (resume top level, doctor
// plan entries) gives the D.4-off text byte-for-byte, and the advice
// counts are restated from the fixture's raw plan JSON by an independent
// implementation of the rules.
//
// With the default thresholds no corpus fixture qualifies (the largest
// eligible history, large-paging, can save well under 32 KiB), so the
// expectation list is empty and every vector is byte-identical to D.3.1.
// TestD4ComparatorOnCorpus runs the same comparator with lowered
// thresholds to prove it works. Note rollover needs an input member no
// oracle vector has, so it cannot change a vector.
//
// SHIORI_D4_UPDATE=1 rewrites the expectation hashes (review the diff).

const d4ExpectationsFile = "d4/expectations.json"

var (
	d4Once    sync.Once
	d4Loaded  d1File
	d4Mu      sync.Mutex
	d4Updated = map[string]d1Expectation{}
)

func d4Update() bool { return os.Getenv("SHIORI_D4_UPDATE") == "1" }

func d4Expectations(t testing.TB) map[string]d1Expectation {
	d4Once.Do(func() {
		data, err := os.ReadFile(testutil.Testdata(d4ExpectationsFile))
		if err == nil {
			err = json.Unmarshal(data, &d4Loaded)
		}
		if err != nil && !d4Update() {
			t.Fatalf("reading %s: %v", d4ExpectationsFile, err)
		}
		if d4Loaded.Vectors == nil {
			d4Loaded.Vectors = map[string]d1Expectation{}
		}
	})
	return d4Loaded.Vectors
}

const d4Note = "D.4 approved design changes (docs/contracts.md §15): oracle vectors whose Go output changes on purpose (compaction advice), with the SHA-256 and UTF-16 length of the pinned Go output (root-normalized). Generated by SHIORI_D4_UPDATE=1 go test ./internal/engine -run TestCorpusParity; every listed vector also passes a comparator against the same engine with the D.4 advice off. Empty: with the default thresholds no corpus fixture is recommended for compaction, so every vector is byte-identical to D.3.1."

func d4Write(t *testing.T) {
	if !d4Update() {
		return
	}
	d4Mu.Lock()
	out := map[string]d1Expectation{}
	for id, x := range d4Updated {
		out[id] = x
	}
	d4Mu.Unlock()
	data, _ := json.MarshalIndent(d1File{Note: d4Note, Vectors: out}, "", "  ")
	if err := os.MkdirAll(testutil.Testdata("d4"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(testutil.Testdata(d4ExpectationsFile), append(data, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	d4Loaded.Vectors = out
	t.Logf("wrote %s (%d vectors)", d4ExpectationsFile, len(out))
}

func d4Candidate(t *testing.T, v *vector, text, offText string) bool {
	_, listed := d4Expectations(t)[v.ID]
	return listed || text != offText
}

func checkD4(t *testing.T, v *vector, root testutil.Root, text, offText string) string {
	t.Helper()
	if text == offText {
		t.Fatalf("listed in %s but identical to the D.4-off output; remove the entry", d4ExpectationsFile)
	}
	if err := d4Compare(root.Path, v.Call.Tool, text, offText); err != nil {
		t.Fatalf("D.4 comparator: %v", err)
	}
	normalized := root.Normalize(text)
	if d4Update() {
		d4Mu.Lock()
		d4Updated[v.ID] = d1Expectation{Change: "compaction advice", OutputSha256: sha(normalized), RawOutputLength: ojson.UTF16Len(text)}
		d4Mu.Unlock()
		return v.ID + ": D.4 compaction advice (recorded)"
	}
	x, ok := d4Expectations(t)[v.ID]
	if !ok {
		t.Fatalf("output differs on purpose (D.4) but the vector is not listed in %s", d4ExpectationsFile)
	}
	if sha(normalized) != x.OutputSha256 {
		t.Fatalf("D.4 pinned output changed: sha %s want %s (SHIORI_D4_UPDATE=1 to re-pin after review)", sha(normalized), x.OutputSha256)
	}
	if root.SameLength() && ojson.UTF16Len(text) != x.RawOutputLength {
		t.Fatalf("D.4 raw length %d want %d", ojson.UTF16Len(text), x.RawOutputLength)
	}
	return v.ID + ": D.4 " + x.Change
}

// d4Compare removes the advice, compares with the D.4-off text and
// restates each advice from the raw plan JSON.
func d4Compare(root, tool, text, offText string) error {
	parsed, err := ojson.Parse([]byte(text))
	if err != nil {
		return err
	}
	v := parsed.Value
	var advices []ojson.Value
	var ids []string
	switch tool {
	case "workplan_resume":
		a, ok := v.Get("compactionRecommended")
		if !ok {
			return fmt.Errorf("resume output differs without compactionRecommended")
		}
		wp, _ := v.Get("workplan")
		id, _ := wp.Get("id")
		advices, ids = append(advices, a), append(ids, id.Str())
		v = objWithout(v, "compactionRecommended")
	case "workplan_doctor":
		plans, _ := v.Get("plans")
		var out []ojson.Value
		for _, p := range plans.Elems() {
			if a, ok := p.Get("compactionRecommended"); ok {
				id, _ := p.Get("id")
				advices, ids = append(advices, a), append(ids, id.Str())
				p = objWithout(p, "compactionRecommended")
			}
			out = append(out, p)
		}
		v = objReplace(v, "plans", ojson.ArrayValue(out))
	default:
		return fmt.Errorf("no D.4 inverse for %s", tool)
	}
	if len(advices) == 0 {
		return fmt.Errorf("output differs but carries no compactionRecommended")
	}
	inv := string(ojson.Pretty(v))
	if !strings.HasPrefix(text, "{\n") {
		inv = string(ojson.Compact(v))
	}
	if inv != offText {
		return fmt.Errorf("output minus compactionRecommended differs from the D.4-off output\n%s", firstDiff(inv, offText))
	}
	for i, a := range advices {
		if err := d4Restate(root, ids[i], tool, a); err != nil {
			return fmt.Errorf("%s: %v", ids[i], err)
		}
	}
	return nil
}

// d4Restate recomputes the advice counts from the raw plan bytes with an
// independent implementation of the contracts §15 rules.
func d4Restate(root, id, tool string, a ojson.Value) error {
	data, err := os.ReadFile(filepath.Join(root, ".opencode/workplan", id+".json"))
	if err != nil {
		return err
	}
	want, err := restateAdvice(data, DefaultRolloverKeep)
	if err != nil {
		return err
	}
	got := map[string]int{}
	if tool == "workplan_resume" {
		got["notes"] = numMember(a, "notes")
		got["archivable"] = numMember(a, "terminalSteps")
		got["resolved"] = numMember(a, "resolvedFindings")
	} else {
		got["notes"] = numMember(a, "notes", "eligible")
		got["archivable"] = numMember(a, "terminalSteps", "archivable")
		got["terminal"] = numMember(a, "terminalSteps", "total")
		got["resolved"] = numMember(a, "resolvedFindings", "count")
		for _, k := range []string{"pinned", "decision", "openReference", "archivePointer", "latest"} {
			got["kept."+k] = numMember(a, "notes", "kept", k)
		}
		if j := numMember(a, "estimate", "json", "before"); j != len(data) {
			return fmt.Errorf("estimate.json.before %d, file %d bytes", j, len(data))
		}
	}
	for k, g := range got {
		if want[k] != g {
			return fmt.Errorf("%s: advice %d, restated %d", k, g, want[k])
		}
	}
	return nil
}

var (
	d4DecisionRe = regexp.MustCompile(`(?i)\b(decision|decisions|decided)\b`)
	d4UserRe     = regexp.MustCompile(`\bUSER\b`)
)

// restateAdvice is the test's own statement of the rules (contracts §15):
// archivable = completed phases whose every step is completed; terminal =
// completed or cancelled steps; resolved = findings with status resolved;
// rollover keeps the latest keep notes and older notes that are pinned,
// decision records, name an open step / quote an open finding title, or
// are compaction archive pointers.
func restateAdvice(data []byte, keep int) (map[string]int, error) {
	var p struct {
		Phases []struct {
			ID     string `json:"id"`
			Status string `json:"status"`
			Steps  []struct {
				ID     string `json:"id"`
				Status string `json:"status"`
			} `json:"steps"`
		} `json:"phases"`
		Findings []struct {
			Title  string  `json:"title"`
			Status *string `json:"status"`
		} `json:"reviewFindings"`
		Notes []string `json:"notes"`
	}
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	out := map[string]int{}
	var openSteps, openTitles []string
	for _, ph := range p.Phases {
		all := ph.Status == "completed" && len(ph.Steps) > 0
		for _, st := range ph.Steps {
			done := st.Status == "completed" || st.Status == "cancelled"
			if done {
				out["terminal"]++
			} else {
				openSteps = append(openSteps, ph.ID+"/"+st.ID)
			}
			all = all && st.Status == "completed"
		}
		if all {
			out["archivable"] += len(ph.Steps)
		}
	}
	for _, f := range p.Findings {
		if f.Status != nil && *f.Status == "resolved" {
			out["resolved"]++
		} else if t := strings.TrimSpace(f.Title); ojson.UTF16Len(t) >= 12 {
			openTitles = append(openTitles, t)
		}
	}
	names := func(n string) bool {
		for _, s := range openSteps {
			re := regexp.MustCompile(`(^|[^A-Za-z0-9_-])` + regexp.QuoteMeta(s) + `($|[^A-Za-z0-9_-])`)
			if re.MatchString(n) {
				return true
			}
		}
		for _, t := range openTitles {
			if strings.Contains(n, t) {
				return true
			}
		}
		return false
	}
	cut := len(p.Notes) - keep
	if cut < 0 {
		cut = 0
	}
	out["kept.latest"] = len(p.Notes) - cut
	for _, n := range p.Notes[:cut] {
		switch {
		case strings.Contains(strings.ToLower(n), "[pinned]"):
			out["kept.pinned"]++
		case d4DecisionRe.MatchString(n) || d4UserRe.MatchString(n):
			out["kept.decision"]++
		case names(n):
			out["kept.openReference"]++
		case strings.HasPrefix(n, "Compaction archive: "):
			out["kept.archivePointer"]++
		default:
			out["notes"]++
		}
	}
	return out, nil
}

// TestD4ComparatorOnCorpus runs the D.4 comparator on corpus vectors with
// lowered thresholds, so that the fixtures with eligible history get the
// advice: the output minus the advice equals the D.4-off output and the
// counts restate from the raw plan.
func TestD4ComparatorOnCorpus(t *testing.T) {
	low := &CompactionThresholds{MinSavingsBytes: 1, Notes: 1, TerminalPercent: 1, PlanBytes: 1}
	advised, budgetCost := 0, 0
	for _, f := range loadVectors(t, "tools", "resume") {
		var v vector
		data, _ := os.ReadFile(f)
		if err := json.Unmarshal(data, &v); err != nil {
			t.Fatal(err)
		}
		if v.Call.Tool != "workplan_doctor" && v.Call.Tool != "workplan_resume" {
			continue
		}
		t.Run(v.ID, func(t *testing.T) {
			root := testutil.NewRoot(t, v.Fixture)
			e := mustEngine(t, root.Path)
			e.Compaction = low
			input, err := ojson.Parse(v.Call.Input)
			if err != nil {
				t.Fatal(err)
			}
			text, err := runTool(t, e, v.Call.Tool, input.Value)
			if err != nil {
				return
			}
			off := *e
			off.noD4 = true
			offText, _ := runTool(t, &off, v.Call.Tool, input.Value)
			if text == offText {
				return
			}
			// A resume packet whose budget is tight pays for the advice
			// with a page item or shorter text (it is dropped only before
			// text would go below the D.1 minimums), so it differs in more
			// than the member; the comparator applies to the others.
			if v.Call.Tool == "workplan_resume" && (truncated(t, text) || truncated(t, offText) ||
				pageReturned(parseT(t, text)) != pageReturned(parseT(t, offText))) {
				budgetCost++
				return
			}
			if err := d4Compare(root.Path, v.Call.Tool, text, offText); err != nil {
				t.Fatal(err)
			}
			advised++
		})
	}
	if advised == 0 {
		t.Fatal("no corpus vector exercised the D.4 comparator")
	}
	t.Logf("D.4 comparator checked %d vectors with lowered thresholds; %d small-budget resume packets paid for the advice with page items or text and were skipped", advised, budgetCost)
}

func truncated(t *testing.T, text string) bool {
	return numMember(parseT(t, text), "truncatedFieldCount") > 0
}
